### ISSUE TITLE
Extended DateTimeImmutable cannot be set to property

### ISSUE THREAD

**Issue by snapshotpl** [phpstan/phpstan-doctrine#103]
```
Property MyEntity::$creationTime type  
         mapping mismatch: database can contain DateTimeImmutable but property   
         expects Safe\DateTimeImmutable. 
```
[`Safe\DateTimeImmutable`](https://github.com/thecodingmachine/safe/blob/master/lib/DateTimeImmutable.php#L16) extends `\DateTimeImmutable`

**Comment by ondrejmirtes** [comment]
Do you have custom type to achieve this? How does the property annotation (phpDoc) looks like?

**Comment by snapshotpl** [comment]
I have default `datetime_immutable` type.
```
    /**
     * @var DateTimeImmutable
     *
     * @ORM\Column(type="datetime_immutable")
     */
    private $placedDatetime;
```

**Comment by ondrejmirtes** [comment]
1) Do you have `use Safe\DateTimeImmutable` above the class?
2) How do you achieve that Doctrine hydrates `Safe\DateTimeImmutable` into the property?

**Comment by snapshotpl** [comment]
1. Yes
2. I miss that case...

**Comment by ondrejmirtes** [comment]
So what’s PHPStan telling you that you won’t always have Safe\DateTimeImmutable in the property so you should change the @var to \DateTimeImmutable.

**Comment by snapshotpl** [comment]
Thanks God for phpstan! ;) I will create custom type for this case because I want to have always `Safe\DateTimeImmutable`

**Comment by ondrejmirtes** [comment]
Make sure to follow this section https://github.com/phpstan/phpstan-doctrine#custom-types to let PHPStan know about the custom type :) You can also set `doctrine.reportUnknownTypes` to true (https://github.com/phpstan/phpstan-doctrine/blob/master/rules.neon#L4) to find out what other types need custom descriptors...
