### ISSUE TITLE
Unable to validate field on findOneBy*

### ISSUE THREAD

**Issue by Slamdunk** [phpstan/phpstan-doctrine#106]
Hi, on my project the extension works great, except for `findOneBy*` methods-like.

I was unable to reproduce the bug within this repository, but I've created a dedicated one that shows the issue:
https://github.com/Slamdunk/phpstan-doctrine-bug
And this is the output of the build:
https://travis-ci.org/Slamdunk/phpstan-doctrine-bug/builds/638002155#L238-L241
I expect the error on `findOneByXyz` but not on `findOneByUsername`.

I've committed both the composer.json and composer.lock so you can deep down the versions, which are:

1. PHP 7.3.12
1. PHPStan 0.12.5
1. PHPStan Doctrine 0.12.9
1. Doctrine ORM 2.7.0

**Comment by ondrejmirtes** [comment]
Hi,
I've just sent you a PR with all the necessary changes needed to reach the expected output: https://github.com/Slamdunk/phpstan-doctrine-bug/pull/1

PHPStan needs to know entity metadata to know that `findOneByUsername` exists, so you need to provide the `objectManagerLoader`. Ideally, it should match EntityManager from your application, so the best way to do it is to obtain it through your DI container, as described in the README: https://github.com/phpstan/phpstan-doctrine/#configuration

Additional benefits of this are described in this article: https://medium.com/@ondrejmirtes/phpstans-doctrine-extension-just-got-a-lot-better-2e0f5af68723

**Comment by Slamdunk** [comment]
Thank you very much for replying quickly and thoroughly.

I already was providing `objectManagerLoader`, but I was missing the `@extends EntityRepository<MyEntity>` annotation into the repository classes.

Still, cheers for finding the time to code the reply :beer:
