### ISSUE TITLE
Specifying TEntityClass

### ISSUE THREAD

**Issue by gjuric** [phpstan/phpstan-doctrine#114]
I am getting an error:

`
Class MyRepository extends generic class Doctrine\ORM\EntityRepository but does not specify its types:  TEntityClass`

What would be the proper way to inform phpstan about the entity being handled by this repository?

**Comment by ondrejmirtes** [comment]
Please read this article: https://medium.com/@ondrejmirtes/generics-in-php-using-phpdocs-14e7301953

The whole article is good to know about, but this specific section talks about your problem:

> When implementing a generic interface or extending a generic class, you have two options:

**Comment by gjuric** [comment]
I've read the article, but having more concrete examples would be helpful.

**Comment by ondrejmirtes** [comment]
Referring to:

When implementing a generic interface or extending a generic class, you have two options:

* Preserve the genericness of the parent, the child class will also be generic
* Specify the type variable of the interface/parent class. The child class will not be generic.

So:

```php
/**
 * @template TEntityClass of object
 * @extends \Doctrine\ORM\EntityRepository<TEntityClass>
 */
class MyRepository extends \Doctrine\ORM\EntityRepository
```

or for example:

```php
/**
 * @extends \Doctrine\ORM\EntityRepository<UserEntity>
 */
class MyRepository extends \Doctrine\ORM\EntityRepository
```

**Comment by gjuric** [comment]
Thank you very much!
