### ISSUE TITLE
Type descriptors don't work

### ISSUE THREAD

**Issue by ossinkine** [phpstan/phpstan-doctrine#116]
The last major release introduce the feature to find entity properties with not the same type as according column.

I'm trying to check this but PHPStan does not find these properties.

To demonstrate this behavior I've created a [reproducer](https://github.com/ossinkine/phpstan-doctrine-type-descriptors). In the last commit I changed the column type but didn't change property type and I expect the PHPStan warn this but there are no errors.

How can I enable this feature or what do I do wrong?

**Comment by ondrejmirtes** [comment]
Hi, this is a nice issue, the reproducer helps a lot :) You forgot to also include `rules.neon` from this extension. [See README](https://github.com/phpstan/phpstan-doctrine/#installation).

The easiest way to avoid this problem in the future is to use [phpstan/extension-installer)(https://github.com/phpstan/extension-installer).
