### ISSUE TITLE
[FEATURE] Allow functions chained on execute()

### ISSUE THREAD

**Issue by tomasnorre** [phpstan/phpstan-doctrine#117]
I would like to suggest a rule to have following functions allowed to have `fetch()`, `fetchAll()`, `fetchColumn()` and `rowCount()` chained after `execute()` without getting the errors

```
Cannot call method fetch() on Doctrine\DBAL\Driver\Statement|int.
Cannot call method fetchAll() on Doctrine\DBAL\Driver\Statement|int.
Cannot call method fetchColumn() on Doctrine\DBAL\Driver\Statement|int.
Cannot call method rowCount() on Doctrine\DBAL\Driver\Statement|int.
```

The `execute()` returns `int` when a `count('*')` is made instead of a `select('*')`, therefor with two possible return types PHPStan complains about this.

### Code Example

```
$queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable($this->tableName);
$queueRec = $queryBuilder
    ->select('*')
    ->from($this->tableName)
    ->where(
        $queryBuilder->expr()->eq('qid', $queryBuilder->createNamedParameter($queueId))
    )
    ->execute()
    ->fetch();
```

My problem currently, as stated on twitter, I'm quite new to PHPStan and would not know where to start to add this rule.

If someone can point me into the direction how to implement this, I would happy to have a look at this, and I don't see it as a error with the current implementation of Doctrine `select()` and `count()`.

Hope that someone can point me in the right direction.

**Comment by ondrejmirtes** [comment]
Hi, this isn't a case for a new rule as you're just trying to prevent a false positive. This is a case for a dynamic return type extension (https://phpstan.org/developing-extensions/dynamic-return-type-extensions). You need one for `execute()` and walk up the `MethodCall` AST chain to see if `select` or `count` was called at the beginning...

It's easy to write the extension for this case:

```php
$queryBuilder
    ->select('*')
    ->from($this->tableName)
    ->where(
        $queryBuilder->expr()->eq('qid', $queryBuilder->createNamedParameter($queueId))
    )
    ->execute()
    ->fetch();
```

It's a little bit harder to write it for this case:

```php
$tmp = $queryBuilder
    ->select('*')
    ->from($this->tableName)
    ->where(
        $queryBuilder->expr()->eq('qid', $queryBuilder->createNamedParameter($queueId))
    );
$tmp->execute()->fetch();
```

But we can start supporting only the first one as that will cover most uses I think.

**Comment by tomasnorre** [comment]
Thanks for your input, I'll have a look.

**Comment by mitelg** [comment]
hey @tomasnorre 
I'm also interested in this. did you already get a solution for this?

**Comment by tomasnorre** [comment]
No unfortunately I didn't get to it. Would love to join forces if we can move it forward.

**Comment by tomasnorre** [comment]
Looks like it was addressed before 
https://github.com/phpstan/phpstan/issues/687

**Comment by mitelg** [comment]
hey,
yesterday @shyim @Christian-Rades and me hacked around a bit and this is what we got so far 
```
 <?php declare(strict_types=1);
 namespace Shopware\Development\Analyze\PHPStan\Rules\DoctrineDbal;
 use Doctrine\DBAL\Driver\Statement;
 use Doctrine\DBAL\Query\QueryBuilder;
 use PhpParser\Node\Expr\MethodCall;
 use PhpParser\Node\Expr\Variable;
 use PhpParser\Node\Stmt\ClassMethod;
 use PhpParser\NodeDumper;
 use PhpParser\NodeFinder;
 use PHPStan\Analyser\Scope;
 use PHPStan\Reflection\MethodReflection;
 use PHPStan\Reflection\ParametersAcceptorSelector;
 use PHPStan\Type\ClassStringType;
 use PHPStan\Type\DynamicMethodReturnTypeExtension;
 use PHPStan\Type\IntegerType;
 use PHPStan\Type\ObjectType;
 use PHPStan\Type\Type;
 use PHPStan\Type\UnionType;
 class QueryBuilderDynamicReturnTypeExtension implements DynamicMethodReturnTypeExtension
 {
     public function getClass(): string
     {
         return QueryBuilder::class;
     }
     public function isMethodSupported(MethodReflection $methodReflection): bool
     {
         return $methodReflection->getName() === 'execute';
     }
     public function getTypeFromMethodCall(
         MethodReflection $methodReflection,
         MethodCall $methodCall,
         Scope $scope
     ): Type {
         $var = $methodCall->var;
         while ($var instanceof MethodCall) {
             if ((string) $var->name === 'select' || (string) $var->name === 'addSelect') {
                 return new ObjectType(Statement::class);
             }
             $var = $var->var;
         }
 
         $varName = (string) $var->name;
 
         // Get class method node
         $classMethodNode = $var;
         while (! $classMethodNode instanceof ClassMethod) {
             $classMethodNode = $classMethodNode->getAttribute('parent');
         }
 
         /** @var MethodCall[] $methodCallNodes */
         $methodCallNodes = (new NodeFinder())->findInstanceOf([$classMethodNode], MethodCall::class);
 
         foreach ($methodCallNodes as $methodCallNode) {
             if (! $methodCallNode->var instanceof Variable) {
                 continue;
             }
 
             if ((string) $methodCallNode->var->name !== $varName) {
                 continue;
             }
 
             if ((string) $methodCallNode->name === 'select' || (string) $methodCallNode->name === 'addSelect') {
                 return new ObjectType(Statement::class);
             }
             
             // Todo: Add nested method call support
         }
 
         return new UnionType([new ObjectType(Statement::class), new IntegerType()]);
     }
 }
```

@ondrejmirtes do you think this is already in a state, worth putting it into a PR? 🙂

**Comment by tomasnorre** [comment]
@mitelg I have the "same" functions for `getClass()` and `isMethodSupported()`, but I never get into the `isMethodSupported()` function. 

I have this registered in the `extension.neon`

```neon
-
    class: PHPStan\Type\Doctrine\QueryBuilder\QueryBuilderExecDynamicReturnTypeExtension
    tags:
        - phpstan.broker.dynamicMethodReturnTypeExtension
``` 

Did you register it differently?

**Comment by shyim** [comment]
Also as `phpstan.broker.dynamicMethodReturnTypeExtension`

**Comment by tomasnorre** [comment]
Even with your suggestion I don't get into the `isMethodSupported()`, I'm wondering if my `QueryBuilder::class` is something else than I expected.

Where my QueryBuilder  is generated it's `\Doctrine\DBAL\Query\QueryBuilder::class` so that looks the same too me.

**Comment by ondrejmirtes** [comment]
@mitelg If the code works for you, definitely open a PR, we can polish it in a review :)

**Comment by mitelg** [comment]
nice, I will go for it next year 😉😁

**Comment by mitelg** [comment]
@tomasnorre 
yes it should be `Doctrine\DBAL\Query\QueryBuilder` as you can see at the imports

**Comment by tomasnorre** [comment]
Thanks for taking care.
