### ISSUE TITLE
Configuration requires extension installer

### ISSUE THREAD

**Issue by pavlakis** [phpstan/phpstan-doctrine#118]
Upgrading from `0.11.5` to a `0.12.12` release (actually got this previously with any `0.12.*`), will get the following error:

```
Unexpected option 'parameters › doctrine', 'parameters › symfony', 'parameters › includes'.
```

Installing `phpstan/extension-installer` resolves the first part of this, apart from the `includes` option:
```
Unexpected option 'parameters › includes'.
```

The documentation is not clear on this. 
If the manual installation is no longer an option, I can create a PR to update the docs.

**Comment by ondrejmirtes** [comment]
It's possible you didn't use this extension at all on 0.11.x (silently) which explains the messages you're seeing. Please refer to the manual installation section in the README: https://github.com/phpstan/phpstan-doctrine#installation

Most likely you're putting `includes` section under `parameters`, but it should be at the top level.

Of course `extension-installer` fixes this but it's not required at all.

**Comment by pavlakis** [comment]
@ondrejmirtes Thank you for your explanation
