### ISSUE TITLE
Make Doctrine Collection stub to enable generics

### ISSUE THREAD

**Issue by ikvasnica** [phpstan/phpstan-doctrine#122]
Hi, 

I haven't found a way to use Doctrine collections with PHPStan generics. Is there a plan to implement it?

This code:
```
use Doctrine\Common\Collections\ArrayCollection;

/**
* @extends ArrayCollection<MyObject>
*/
class CustomCollection extends ArrayCollection
```

leads to the error:
```
Class                                                                  
         CustomCollection   
         @extends tag contains incompatible type                                
         Doctrine\Common\Collections\ArrayCollection&iterable<MyObject>.
```

Thanks for considering the feature or your suggestions in case I have misunderstood something. 🙂

**Comment by ondrejmirtes** [comment]
I agree this message is a bit obscure :) But `ArrayCollection` defines two type variables: https://github.com/doctrine/collections/blob/a4504c79efd8847cc77d10b70209ef838b10338f/lib/Doctrine/Common/Collections/ArrayCollection.php#L39-L40

So you need `ArrayCollection<int, MyObject>`.

**Comment by ikvasnica** [comment]
@ondrejmirtes Thank you, it works great!
