### ISSUE TITLE
PHPStan\Analyser\LazyScopeFactory::create() must be of the type array, object given

### ISSUE THREAD

**Issue by iluuu1994** [phpstan/phpstan-doctrine#133]
Thanks for PHPStan 0.12.26!

> Internal error: Argument 3 passed to PHPStan\Analyser\LazyScopeFactory::create() must be of the type array, object given, called in .../vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/QueryBuilder/QueryBuilderMethodDynamicReturnTypeExtension.

Our pipeline fails today. Was this BC break intentional?

**Comment by ondrejmirtes** [comment]
I tagged phpstan-doctrine 0.12.14 with a fix right after releasing PHPStan 0.12.26 :) https://github.com/phpstan/phpstan-doctrine/issues/132

**Comment by ondrejmirtes** [comment]
So if your pipelines automatically update phpstan/phpstan but not phpstan-doctrine, you should look into that.

**Comment by iluuu1994** [comment]
Well, our nightly ran four hours after you tagged phpstan-doctrine. We don't commit the composer.lock in that projekt so it should've been up to date. I'll check the logs to be sure and rerun the pipeline manually 🙂

**Comment by iluuu1994** [comment]
You were right, we were fixed on a previous version of doctrine/persistence and forgot. Sorry 😕 Maybe there should be a conflict though in phpstan so that it doesn't get installed with phpstan-doctrine <0.12.14.
