### ISSUE TITLE
Version 0.12.14 conflicts with  doctrine/persistence[1.1.1]

### ISSUE THREAD

**Issue by ANZI999** [phpstan/phpstan-doctrine#134]
When trying to upgrade the version from 0.12.13 to 0.12.14 composer reports a conflict.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpstan/phpstan-doctrine 0.12.14 conflicts with doctrine/persistence[1.1.1].
    - phpstan/phpstan-doctrine 0.12.14 conflicts with doctrine/persistence[1.1.1].
    - phpstan/phpstan-doctrine 0.12.14 conflicts with doctrine/persistence[1.1.1].
    - Installation request for phpstan/phpstan-doctrine ^0.12.14 -> satisfiable by phpstan/phpstan-doctrine[0.12.14].
    - Installation request for doctrine/persistence (locked at 1.1.1) -> satisfiable by doctrine/persistence[1.1.1].

**Comment by ondrejmirtes** [comment]
This is done on purpose as there's no way to support doctrine/persistence v1.1 and v2.0 at the same time. See https://github.com/phpstan/phpstan-doctrine/issues/130.

You shouldn't have any problems upgrading from v1.1 to v1.3.

**Comment by ANZI999** [comment]
That did the trick. Thank you for quick answers.
