### ISSUE TITLE
Possible regression on findBy* magic method

### ISSUE THREAD

**Issue by bmehdi** [phpstan/phpstan-doctrine#136]
Hello, following `findOneBy*` magic method call works fine on phpstan 0.11.19 and phpstan-doctrine 0.11.6 even at level 7 but fails on phpstan 0.12.30 and phpstan-doctrine 0.12.17 :

```
class FooRepository extends Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository
{
    ...
   public function fooFunction()
   {
       return $this->findOneByFoo();
   }
    ...
}
```

Error message in output  is :

```
 ------ --------------------------------------------------------------------------------------- 
  Line   src/AppBundle/Repository/FooRepository.php                                            
 ------ --------------------------------------------------------------------------------------- 
  107    Call to an undefined method AppBundle/Repository/FooRepository::findOneByFoo().  
 ------ --------------------------------------------------------------------------------------- 
```

**Comment by ondrejmirtes** [comment]
So these magic methods are much more precise on PHPStan 0.12. Previously all `findBy*` methods were considered known. Currently we're looking at the type variable of Doctrine\ORM\EntityRepository (in context of generics https://phpstan.org/blog/generics-in-php-using-phpdocs) to figure out about which entity the repository class is.

To have PHPStan know `findOneByFoo`, you have to specify the entity class above FooRepository, for example like this:

```php
/**
 * @extends Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository<Foo>
 */
class FooRepository extends Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository
```

**Comment by ondrejmirtes** [comment]
We could fall back on having all methods as known if the class isn't specified and let PHPStan's level 6 tell you about that you need to specify the type variable (and make the analysis more precise)...

**Comment by bmehdi** [comment]
Thanks for the response. I probably missed something but the generics does not seem to work for me. For example, in the minimalist Symfony app https://github.com/bmehdi/symfony-app which i just initialized using Symfony documentation, I had the output :
```
vendor/bin/phpstan analyse src --level 2

 ------ ----------------------------------------------------------------------- 
  Line   Controller/LuckyController.php                                         
 ------ ----------------------------------------------------------------------- 
  16     Call to an undefined method App\Repository\FooRepository::findById().  
 ------ ----------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 1 error

**Comment by ondrejmirtes** [comment]
It's sufficient to follow the Configuration section from the README: https://github.com/phpstan/phpstan-doctrine#configuration

I've sent you a PR with the correct setup: https://github.com/bmehdi/symfony-app/pull/1

**Comment by bmehdi** [comment]
Thanks. It works fine for me.

For who needs it, a `tests/object-manager.php` compatible with Symfony 3 :
```
<?php

require __DIR__.'/../vendor/autoload.php';

$kernel = new AppKernel('test', false);
$kernel->boot();

return $kernel->getContainer()->get('doctrine')->getManager();
