### ISSUE TITLE
 Property App\Entity\Website::$rights with generic interface Doctrine\Common\Collections\Collection does not specify its types: TKey, T 

### ISSUE THREAD

**Issue by allan-simon** [phpstan/phpstan-doctrine#142]
I have the following entity

```php
<?php
declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity()
 *
 */
class Website
{


    /**
     * One product has many features. This is the inverse side.
     * @ORM\OneToMany(targetEntity="WebsiteRight", mappedBy="website")
     * @var Collection<WebsiteRight>&iterable<WebsiteRight>
     */
    private $rights;
}
```

and when I run phpstan in level 6 I got the following error

```
 Property App\Entity\Website::$rights with generic interface Doctrine\Common\Collections\Collection does not specify its types: TKey, T 
```

However it seems to be done like expected 

https://github.com/phpstan/phpstan-doctrine/blob/8151e1a258897809dd73806f2070ea0def787c39/tests/Rules/Doctrine/ORM/data/EntityWithRelations.php#L81

Is there a way to please phpstan without turning off the rule ?

**Comment by ondrejmirtes** [comment]
The correct way is to write `@var Collection<int, WebsiteRight>` because Collection has two type variables: TKey and T.

**Comment by allan-simon** [comment]
thanks it works
