### ISSUE TITLE
QueryBuilderDqlRule requires connection to an existing server with existing database

### ISSUE THREAD

**Issue by Majkl578** [phpstan/phpstan-doctrine#144]
It appears that the following code triggers DB connection and eventually crashes if the server or database is unavailable (PDO MySQL DBAL driver):
https://github.com/phpstan/phpstan-doctrine/blob/207a6aedf0ca95c57fb041f3b3c82bcb6e66ad27/src/Rules/Doctrine/ORM/QueryBuilderDqlRule.php#L95-L97
That is because `getSQL()` indirectly invokes `Connection::quote()` which triggers the DB connection, at least with `PDO`.

If the purpose of `QueryBuilderDqlRule` is only DQL syntax validation (as it seems from the `catch` block) then I'd recommend using `getAST()` instead of `getSQL()` as it performs the parsing & AST building part without walking the AST down into an SQL.

Backtrace:
```
vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182
vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169
vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:30
vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1753
vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:911
vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:467
vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:987
vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:1196
vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:852
vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:830
vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:535
vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php:42
vendor/doctrine/orm/lib/Doctrine/ORM/Query/SqlWalker.php:288
vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:405
vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:286
vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:210
vendor/phpstan/phpstan-doctrine/src/Rules/Doctrine/ORM/QueryBuilderDqlRule.php:96
```

**Comment by ondrejmirtes** [comment]
Please send a PR and verify that your fix works.

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-doctrine/commit/a4966eee1fb42383e752e9c84bd5b7b07b01e57a
