### ISSUE TITLE
Add validation for default boolean values

### ISSUE THREAD

**Issue by alexander-schranz** [phpstan/phpstan-doctrine#157]
I just come up with this idea and wanted to share it here, mostly when having a `boolean` value in your entity you initialize it with a specific state (false or true) e.g.:

```php
/**
 * @var boolean
 */
private $enabled = false;
```

This is not automatically used as default value in the database. It would be nice if there doctrine phpstan extension has an additional check for this so its validated and suggest to add a default value to the doctrine mapping:

```diff
-<field name="enabled" type="boolean" column="enabled" nullable="false"/>
+<field name="enabled" type="boolean" column="enabled" nullable="false">
+    <options>
+        <option name="default">0</option>
+    </options>
+</field>
```

**Comment by ondrejmirtes** [comment]
I don't get it - can you share an example with the annotation driver (`@ORM\Column`) and an expected output?

**Comment by alexander-schranz** [comment]
Sure:

**Failing Example**:

```php
/**
 * @var boolean
 *
 * @ORM\Column(name="enabled", type="boolean")
 */
private $enabled = false;
```

**Expected Output**

```bash
The "MyObject::enabled" has a default value "false" but this was not set in the doctrine mapping for the "enabled" field as option.
```

**Success Example:**

```php
/**
 * @var boolean
 *
 * @ORM\Column(name="enabled", type="boolean", options={"default" : 0})
 */
private $enabled = false;
```

**Comment by ondrejmirtes** [comment]
Hi, I understand why you'd want this for consistency, but not having the `default` in the database mapping doesn't actually represent a bug that would break something in your application...

**Comment by alexander-schranz** [comment]
Yeah I understand this, we had the problem that a boolean field was added lately to a schema in @sulu. MySQL had no problems to add it, but PostgreSQL did fail because of no default was defined for that column. So it was kind of a bug which did break the application. I understand that not all will need this and that it would need to have a flag for it to activate it, but it could reduce bugs in deployments.

**Comment by ondrejmirtes** [comment]
Can you describe the steps of what did you do and what happened that resulted in a bug?
