### ISSUE TITLE
Plugin License

### ISSUE THREAD

**Issue by p365labs** [phpstan/phpstan-doctrine#160]
Hi everyone, is there a specific reason why this plugin doesn't have a LICENSE file?
if u want I can add one. Which LICENSE should be? the same of [PhpStan](https://github.com/phpstan/phpstan)?

**Comment by ondrejmirtes** [comment]
There's MIT specified in composer.json, so feel free to add the same one. Also feel free to go through the other repos https://github.com/phpstan and check if it's also missing somewhere else. Thank you!
