### ISSUE TITLE
Magic methods : Call to an undefined method

### ISSUE THREAD

**Issue by jcerri** [phpstan/phpstan-doctrine#166]
Since nobody has complained before, I may be missing something obvious.
I'm getting this error while calling some magic method : 
`Call to an undefined method App\Repository\MyRepository<App\Entity\MyEntity>::findOneByField()`

My code looks like this : 
```
$myRepository = $em->getRepository(MyEntity::class);
$myRepository->findOneByField($field);
```

I have configured the objectManagerLoader as specified in the documentation for a Symfony app.

**Comment by jcerri** [comment]
It is working in another context, I close the issue.

**Comment by ondrejmirtes** [comment]
My guess is that MyEntity doesn't have $field persisted property.

**Comment by ondrejmirtes** [comment]
Also, how App\Repository\MyRepository looks like?

**Comment by jcerri** [comment]
```
namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

class MyRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, MyEntity::class);
    }
}
```

```
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MyRepository")
 */
class MyEntity
{
    /**
     * @var string
     *
     * @ORM\Column(name="field", type="string", length=255, unique=true)
     */
    private $field;
}
```

**Comment by ondrejmirtes** [comment]
On level 6 you'd get this error:

```
Class App\Repository\MyRepository extends generic class Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository but does not specify its types: TEntityClass
```

This will get rid of the error for you:

```
/**
 * @extends ServiceEntityRepository<MyEntity>
 */
class MyRepository extends ServiceEntityRepository
```

And I guess it will help you to get rid of this error too: "Call to an undefined method..."

**Comment by jcerri** [comment]
Indeed, I don't get the error anymore using the @extends annotation, thanks for your help.
