### ISSUE TITLE
phpstan/phpstan-doctrine is not compatible with doctrine 3

### ISSUE THREAD

**Issue by petrparolek** [phpstan/phpstan-doctrine#168]
```
phpstan-doctrine version:  0.12.27 and dev-master e5d9646

Doctrine packages versions:

doctrine/annotations                           1.11.1
doctrine/cache                                 1.10.2
doctrine/collections                           1.6.7
doctrine/common                                3.1.0
doctrine/dbal                                  2.10.4
doctrine/event-manager                         1.1.1
doctrine/inflector                             2.0.3
doctrine/instantiator                          1.4.0
doctrine/lexer                                 1.2.1
doctrine/orm                                   2.8.1
doctrine/persistence                           2.1.0
nettrine/annotations                           v0.7.0
nettrine/cache                                 v0.3.0
nettrine/dbal                                  v0.7.0
nettrine/orm                                   v0.8.1
```

PHP code:

```
	/**
	 * @param int[] $ids
	 * @return ArrayCollection|Collection<int, PaymentTag>
	 */
	public function findTagsByIds(array $ids): Collection
	{
		$criteria = Criteria::create()
			->where(Criteria::expr()->in('id', $ids))
			->orderBy(['title' => 'ASC']);

		return $this->matching($criteria);
	}
```

`Method App\Repositories\PaymentTagRepository::findTagsByIds() should return Doctrine\Common\Collections\Collection<int, App\Entities\PaymentTag> but returns Doctrine\Common\Collections\Collection<int, T>.`

With Doctrine versions:
```
doctrine/annotations                           1.11.1
doctrine/cache                                 1.10.2
doctrine/collections                           1.6.7
doctrine/common                                2.13.3
doctrine/dbal                                  2.10.4
doctrine/event-manager                         1.1.1
doctrine/inflector                             1.4.3
doctrine/instantiator                          1.4.0
doctrine/lexer                                 1.2.1
doctrine/orm                                   2.7.5
doctrine/persistence                           1.3.8
doctrine/reflection                            1.2.2
```

and phpstan-doctrine version 0.12.27 and dev-master e5d9646 is all right.

**Comment by ondrejmirtes** [comment]
Hi, can you find the definition of the called `matching()` method on GitHub? I don't know which Doctrine package it comes from.

**Comment by petrparolek** [comment]
https://github.com/doctrine/orm/blob/2.8.1/lib/Doctrine/ORM/EntityRepository.php#L308

**Comment by ondrejmirtes** [comment]
I can't reproduce it on a simplified example: https://phpstan.org/r/cb86f860-afe5-4a49-8bc9-a9b81c0205a6

Please create a small reproducing repository that shows your problem.

**Comment by petrparolek** [comment]
https://github.com/petrparolek/phpstan-doctrine-bug/commit/00b08163056228b32af29a0b9fbb39983b4bb873

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-doctrine/commit/723ed14e8f4fbdfa8c0fd7d9601f176444a004eb

It's no longer happening as of phpstan-doctrine 0.12.28.

Also, I really recommend you not to turn off `checkGenericClassInNonGenericObjectType`, the need to add `@extends` etc. in your code also enhances the analysis.

**Comment by petrparolek** [comment]
thank you. Could you show it on my code?

**Comment by ondrejmirtes** [comment]
Your EntityRepository needs to be tagged with:

```php
/**
 * @template T
 * @extends DoctrineEntityRepository<T>
 */
```


And for example your TagRepository needs to be tagged with:

```php
/** @extends EntityRepository<Tag> */
```

**Comment by petrparolek** [comment]
did you mean this https://github.com/petrparolek/phpstan-doctrine-bug/commit/51aa0423c8b727f1034b0f4199126e9bb2e5f916 ? Is code ok?

**Comment by ondrejmirtes** [comment]
Association properties in entities should still be `Collection`. Once they're loaded from the database, it's an instanceof PersistentCollection, not ArrayCollection. Otherwise 👍 .

**Comment by petrparolek** [comment]
https://github.com/petrparolek/phpstan-doctrine-bug/commit/055633e04609f97cf3e0602f66fc83ed92a8c2fd it looks ok
