### ISSUE TITLE
Added Functions for Personal QueryBuilder are not recognized.

### ISSUE THREAD

**Issue by MaxValEh** [phpstan/phpstan-doctrine#179]
I am extending the `Doctrine\ORM\QueryBuilder` to consolidate a filter and a sort function for multiple Repositories.

```php
use Doctrine\ORM\QueryBuilder;

class PersonQueryBuilder extends QueryBuilder
{
    public function addSortByRank(): self
    {
        return $this
            ->orderBy('person_group.rank')
            ->addOrderBy('person.name', 'ASC')
        ;
    }
}
```
Repository:
```php
use App\Doctrine\ORM\QueryBuilder\PersonQueryBuilder;
use App\Entity\Person;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Persistence\ManagerRegistry;

class PersonRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Person::class);
    }

    public function createQueryBuilder($alias, $indexBy = null): PersonQueryBuilder
    {
        return (new PersonQueryBuilder($this->_em))
            ->select($alias)
            ->from($this->_entityName, $alias, $indexBy);
    }

    protected function queryAllSorted(): PersonQueryBuilder
    {
        return $this->createQueryBuilder('person')
            ->innerjoin('person.group', 'person_group')
            ->addSelect('person_group')
            ->addSortByRank()
        ;
    }
}
```
Even though it should be type hinted correctly i do get the following error when using phpstan-doctrine:
```
  Line   root\src\Repository\PersonRepository.php
 ------ -------------------------------------------------------------------------
  51     Call to an undefined method Doctrine\ORM\QueryBuilder::addSortByRank().
```

The error does not appear using phpstan without phpstan-doctrine.

using php 7.4.14, phpstan/phpstan 0.12.80, phpstan/phpstan-doctrine 0.12.32

**Comment by ondrejmirtes** [comment]
Please set the custom doctrine.queryBuilderClass in your phpstan.neon: https://github.com/phpstan/phpstan-doctrine/blob/815dd47ade8120c6850c5a3805649c96fbadbdca/extension.neon#L4

If the problem persists, create a small reproducing repository that shows your problem.

**Comment by ondrejmirtes** [comment]
> Is there a way to declare multiple Classes as queryBuilderClass?

I don't see how it could be possible and what would be the actual use case, do you have a project that uses different child classes in different places?

**Comment by MaxValEh** [comment]
Not yet but i do see the possibility. Hence my question.

I am currently using the PersonQueryBuilder to add filter and sorting functionality to two related Repositories.

If i had two pairs of Repositories that each required common filters i would be interested to do that.

**Comment by ondrejmirtes** [comment]
I think it should be possible to do analysis in that case, but I'd need a small reproducing repository that shows what problems does PHPStan have in such situation.
