### ISSUE TITLE
Type entity property as `numeric-string` while database column type is `string`

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-doctrine#187]
I have an entity with the following column definition:
```php
    /**
     * @ORM\Column(name="amount", type="string")
     */
    private string $amount;
```

Now I want to type that property as `numeric-string` because it will only ever contain numbers anyway.
```php
    /**
     * @var numeric-string
     *
     * @ORM\Column(name="amount", type="string")
     */
    private string $amount;
```

But I'm getting this error:
```
Property MyEntity::$amount type mapping mismatch: database can contain string but property expects string.
```

I don't know how to solve this. Is it even possible?

And is the error message correct? Shouldn't it say: 
```
Property MyEntity::$amount type mapping mismatch: database can contain string but property expects numeric-string.
```

**Comment by ondrejmirtes** [comment]
VerbosityLevel here (https://github.com/phpstan/phpstan-doctrine/blob/d9429f6933dbdaafd6ff87a97ee64a6a134716b5/src/Rules/Doctrine/ORM/EntityColumnRule.php#L147-L165) shouldn't be `typeOnly`, but instead obtained via `getRecommendedLevelByType`.

**Comment by ruudk** [comment]
I'll create a PR to fix that.

**Comment by ruudk** [comment]
I improved the error message in https://github.com/phpstan/phpstan-doctrine/pull/188. 

But I still wonder how I can let it pass.

I want to type the property as `numeric-string` while using the default `string` type for the database column.

**Comment by ondrejmirtes** [comment]
What's PHPStan telling you here is that Doctrine can inject a non-numeric string into your entity. You really need a custom mapping type to make sure that doesn't happen.

Thank you for the PR!
