### ISSUE TITLE
Using `Expr\Literal` in `Expr\Func` breaks return type

### ISSUE THREAD

**Issue by ctrl-f5** [phpstan/phpstan-doctrine#191]
I have the following method:

    private function getTopicConcatExpression(): Expr\Func
    {
        return new Expr\Func('CONCAT_WS', [
            new Expr\Literal("'.'"),
            'event.type.businessDomain',
            'event.type.group',
            'event.type.resource',
            'event.type.subResource',
            'event.type.action',
            'event.type.version',
        ]);
    }

Which, when the doctrine extension is enabled, produces the following error:

>Method App\Repository\EventRepository::getTopicConcatExpression() should return Doctrine\ORM\Query\Expr\Func but returns void

Either disabling the doctrine extension, or replacing `new Expr\Literal("'.'")` with just `'.'` resolves the issue.

I tried coming up with a minimal reproducable example, but to no avail: https://phpstan.org/r/20f26fce-a4a1-46f3-8717-1d884804e2c8

does this tool allow enabling extensions?

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-doctrine/commit/279a808ae73f8db62d5e8ac4ce26d0a8b88d0d66
