### ISSUE TITLE
PHPStan thinks json type can be only array but it can be anything

### ISSUE THREAD

**Issue by simPod** [phpstan/phpstan-doctrine#194]
Doctrine's deprecated `json_array` type is of php type `array` but `json` is of type `mixed`. Extension thinks `json` can only be an `array`.

**Comment by ondrejmirtes** [comment]
I got lost in your description, can you post an example entity with expected vs. actual PHPStan output?

**Comment by simPod** [comment]
See the PR for example. Doctrine `json` type does not hold only arrays but anything that can be stored as json.
