### ISSUE TITLE
'Validates entity fields in repository findBy, findBy*, findOneBy, findOneBy*, count and countBy* method calls' not working anymore

### ISSUE THREAD

**Issue by ThomasTr** [phpstan/phpstan-doctrine#199]
This seems not working anymore with the last version (0.12.42):
```
Validates entity fields in repository findBy, findBy*, findOneBy, findOneBy*, count and countBy* method calls.
```
The result seems to be recognized only as a plain object. I got tons of errors aka

- expects App\Entity\XXX, object given.                                                         
- Call to an undefined method object::getId(). 

After reverting to version 0.12.39 the errors are gone.

Example Call:

```
$ticket = $this->entityManager->getRepository(Ticket::class)->find($ticketId);
```
Using $ticket as parameter in method with type Ticket results in error:
```
Parameter #1 $ticket of method  App\Service::method() expects App\Entity\Ticket,  object given.     
```

**Comment by ondrejmirtes** [comment]
Hi, it's most likely that the type was previously `mixed` for you and that this shows some kind of bug you have in your codebase. Can you please add these calls and let me know what PHPStan outputs for the file?

```php
\PHPStan\dumpType($this->entityManager);
\PHPStan\dumpType($this->entityManager->getRepository(Ticket::class));
\PHPStan\dumpType($this->entityManager->getRepository(Ticket::class)->find($ticketId));
```

Also: are you using the `objectManagerLoader` option or not?

Thanks!

**Comment by ThomasTr** [comment]
Thanks for quick response. Here is the output:

```
Dumped type: Doctrine\ORM\EntityManagerInterface                 
Dumped type: App\Repository\TicketRepository<App\Entity\Ticket>  
Dumped type: mixed     
```
I have this in my phpstan.neon.dist:
```
  doctrine:
    objectManagerLoader: tests/phpstan-object-manager.php
```
with tests/phpstan-object-manager.php:
````
<?php declare(strict_types=1);

use App\Kernel;

require dirname(__DIR__).'/tests/bootstrap.php';

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();

return $kernel->getContainer()->get('doctrine')->getManager();
```

**Comment by ondrejmirtes** [comment]
If the last one is `mixed`, then you cannot be getting this error:

```
Parameter #1 $ticket of method  App\Service::method() expects App\Entity\Ticket,  object given.   
```

Also, are you ever overriding the `find` method in your custom repository classes?

Also, this doesn't make much sense to me: `App\Repository\TicketRepository<App\Entity\Ticket>` - can you show me your generic annotations for your repositories?

**Comment by ThomasTr** [comment]
Sorry, this was the output for version 0.12.39. For version 0.12.42 i get following output:

```
  76     Dumped type: Doctrine\ORM\EntityManagerInterface                       
  77     Dumped type: App\Repository\TicketRepository<App\Entity\Ticket>        
  78     Dumped type: object|null   
```
No i didn't override find methods.

The Repository has no specific annotations:

```
class TicketRepository extends ServiceEntityRepository
{
```
For the entity Ticket
````
#[Entity(repositoryClass: TicketRepository::class)]
#[Table(name: 'table_ticket')]
class Ticket
{
````

**Comment by ondrejmirtes** [comment]
So this error is kind of expected. You should be getting an error stemming from the fact you're missing `@extends` above your `TicketRepository` class:

```php
/** @extends ServiceEntityRepository<Ticket> */
class TicketRepository extends ServiceEntityRepository
{
```

Test this and let me know if it works!

**Comment by ThomasTr** [comment]
It works:
````
  76     Dumped type: Doctrine\ORM\EntityManagerInterface                       
  77     Dumped type: App\Repository\TicketRepository<App\Entity\Ticket>        
  78     Dumped type: App\Entity\Ticket|null    
````
Ok, then this only worked so far because the return type was mixed. Then I will now mark all my repositories accordingly.

Thank you very much for your help and your work.

**Comment by ondrejmirtes** [comment]
If you're on level 6 and NOT have `checkGenericClassInNonGenericObjectType: false` in your phpstan.neon then you should be getting a PHPStan error about the missing `@extends` :)
