### ISSUE TITLE
Doctrine type mismatch for non nullable doctrine properties

### ISSUE THREAD

**Issue by patrick-vandy** [phpstan/phpstan-doctrine#200]
I recently decided to give PHPStan a go, but I'm getting over 1,000 errors for type mismatches on my Doctrine entities, such as:

>type mapping mismatch: property can contain int|null but database expects int

Perhaps I'm missing something, but I don't believe these should be type mismatches. To provide an example:

```php
class MyEntity
{
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @var int|null
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}

$entity = new MyEntity();
$entity->getId(); // this can return null if the entity is not yet hydrated
```

I understand seeing a type mismatch if the property annotation has `nullable=true` and the docblock does not include `null`, this makes sense.

However, there are absolutely times where a property with a `NOT NULL` constraint on the database column may contain a `null` value on the entity's property. It seems PHPStan is making the assumption that an entity is always going to be hydrated, but this simply isn't the case. When you create a new entity, all the properties are going to be `null` regardless of if the database expects those fields to contain `NULL` values or not.

**Comment by ondrejmirtes** [comment]
Hi, PHPStan is right here and warns you about potential issues with your code.

In your specific example, you're missing `@ORM\GeneratedValue()` there, so persisting and flushing the entity will not fill the column with a value, instead it will fail to insert it into the database.

Generally, PHPStan is saving you from this case:

```php
$entity = new MyEntity();
$em->persist($entity);
$em->flush();
```

If you have required columns in your database that you're not providing as constructor parameters, you're in danger of having database reject your entity during flush. Not requiring required values as part of constructor is a bad idea - your entity is in an inconsistent state after creation.

**Comment by patrick-vandy** [comment]
> Hi, PHPStan is right here and warns you about potential issues with your code.
> 
> In your specific example, you're missing `@ORM\GeneratedValue()` there, so persisting and flushing the entity will not fill the column with a value, instead it will fail to insert it into the database.
> 
> Generally, PHPStan is saving you from this case:
> 
> ```
> $entity = new MyEntity();
> $em->persist($entity);
> $em->flush();
> ```
> 
> If you have required columns in your database that you're not providing as constructor parameters, you're in danger of having database reject your entity during flush. Not requiring required values as part of constructor is a bad idea - your entity is in an inconsistent state after creation.

@ondrejmirtes I'm sorry but this is wrong. It was a minimal code example, most of my IDs do have the `generatedValue()` annotation, but even then the ID is not generated until the entity is persisted or flushed, depending on the database vendor. Are you really telling me that my code should just magically know it can never call a getter on a generated column before it has been persisted, or it crashes with a fatal error? Yes, I see what PHPStan is trying to warn against, but again, it's making an assumption that a `NOT NULL` constraint in the database has to match a non null requirement on an entity property, and that doesn't make sense.

To your specific example of protecting against a `NULL` value being inserted into the database, this is why we have `@Assert\NotBlank` annotations and we should be running validation on anything before it is saved to a database. There are many other ways saving an entity could fail, such as maximum length on a string, so you cannot rely on native data types to validate your entities.

Are you really telling me every column with a `NOT NULL` constraint should have a default value? That just isn't consistent with any practices I'm aware of. There are plenty of scenarios where a column cannot be `NULL`, but contains user input and a default value is not practical, such as a `title` field on `Project` entity.

The reason we don't provide default values or constructor parameters is to accommodate [mapping entities directly to forms](https://symfony.com/doc/current/forms.html#processing-forms), which is a very common practice in symfony. If you did provide a default value, then you cannot map that entity directly to a form's data when creating a new record. You can get around that by using models for mapping your forms, but that adds a lot of unnecessary overhead and duplication in many cases.

We used to make our PHP types always match the database like you suggest. When we switched to PHP 7 and started using return types, we had many bugs we had to fix from our getters/setters not allowing `null` types, even if the field had `nullable=false`. For example, when you map an entity to a form, symfony is calling that form's setter behind the scenes to map the form data to the entity. Let's say I have a `$title` property with a setter like:

```php
/**
 * @ORM\Column(name="id", type="integer", nullable=false)
 * @var string
 */
private $title;

public function setTitle(string $title)
```

Now, this entity is mapped to a form type with a `title` field. If a user submits the form with an empty title, behind the scenes symfony is calling:

```php
$myEntity->setTitle(null);
```

Which results in a fatal PHP error and crashes the entire application. Obviously I don't want to crash the entire application in this scenario, instead I want to display a validation warning to let the user know the title field is required. Again, this is why `@Assert` annotations exist and entities should always be validated before saving them to the database.

This is just one of many examples of bugs I have encountered due to entities not allowing null return types on properties.

I like the idea of PHPStan, but I have hard time wanting to use it if it is going to be this opinionated and report on something that is not really an error. I can't help but wonder how many other places it will do this, when I'm encountering this on just level 0.

**Comment by ondrejmirtes** [comment]
My point was that PHPStan doesn't complain about this:

```php
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\GeneratedValue()
     * @ORM\Id
     * @var int|null
     */
    private $id;
```

But rightfully complains about this:

```php
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @var int|null
     */
    private $id;
```

The discrepancy here is that I view entities as the main building block of the domain model of an application. So I disagree with making them worse because they're used in a view layer as dumb DTOs. See this article to read more about this problem: https://blog.martinhujer.cz/symfony-forms-with-request-objects/

If you don't want these errors to be reported, you can always ignore them: https://phpstan.org/user-guide/ignoring-errors But PHPStan's here to make your application more robust, so you should definitely consider that.

**Comment by patrick-vandy** [comment]
@ondrejmirtes Ah, apologies I did not understand your initial reply that adding `GeneratedValue()` will make the error go away. However, the problem still remains for other fields, such as the example of a `$title` property on an object.

I have in fact added this error to the ignore list, but my concern is with how opinionated PHPStan is. I feel like this goes beyond detecting probable bugs, to the point of dictating a specific pattern _(not mapping entities directly to forms)_. Actually, if someone is mapping entities directly to a form, this does the opposite and introduces possible bugs if someone follows the recommendation of PHPStan.

I'm definitely aware of the arguments for separating entities from the view layers and/or forms. I don't disagree with these arguments, and in plenty of cases I use data models when the entity does not map directly to a form, exactly like the article you reference. This is the reason I mentioned this in my first reply.

However, you have to be practical too and make some trade offs. We can all agree that duplication is very bad in code. If you always make a model for your form data, you end up with massive duplication in some cases. 90% percent of the forms in our application do map directly to entities, and if we added models, we would just end up with two classes that look exactly the same. This means when we add a new field or change something, it has to be done in two classes instead of one. It just doesn't make sense to add all that overhead, plus needing code to then hydrate the entity from the model.

I see where PHPStan is coming from on this, and I agree there are times you should use data models for forms instead of entities, but I don't think PHPStan should be dictating that I always use model objects with forms. That is a design pattern, not a probable bug.

Anyway, thanks for the explanation and response. I appreciate it.

**Comment by ondrejmirtes** [comment]
Hi, PHPStan core isn't opinionated at all, it's trying to prevent runtime errors and other weird code that might be a coding mistake. As you increase the level, the reported errors are more theoretical in nature but can still help you by preventing mistakes in production.

Extensions also aren't opinionated, with the exception of phpstan-strict-rules.

phpstan-doctrine has optional rules (you enabled them by including rules.neon, or extension-installer unavoidably enables them for you) that focus on differences between property and Column types. With your coding style, these rules cannot perform any useful service for you, so just ignore them. Or make them help you understand how vulnerable application is, maybe baseline the existing errors, and try writing your new entities in a better way.

**Comment by VincentLanglet** [comment]
TLDR: Would it be possible to re-open the issue to introduce an option about this behavior @ondrejmirtes ?
By default it forbid `null` for `non-nullable` property, but the option would allow it.

This avoid to ignore the error and will let people in my case to
- Not have error for `@var string|null` with `@ORM\Column(name="title", type="string", nullable=false)`
- Still have error for `@var int|null` with `@ORM\Column(name="title", type="string", nullable=false)`

---------------------
I just encounter this issue because I tried to enable the doctrines rules.

I understand the "You should not use Entities as DTO" point of view. But this is very opinionated, here are different point of view:
- Looking at the symfony/demo code https://github.com/symfony/demo/blob/main/src/Entity/Post.php getter have nullable typehint even if the database property is not nullable (and even if the class property has not null in the phpdoc).

- Looking at the doctrine doc https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/tutorials/getting-started.html#adding-behavior-to-entities, it recommend DTO, but also have the following code
```
$product = new Product();
$product->setName($newProductName);

$entityManager->persist($product);
$entityManager->flush();
```
where `getName()` returns `null` before setting it.

- Looking at the symfony doc https://symfony.com/doc/current/doctrine.html#persisting-objects-to-the-database non-nullable property are set AFTER calling `new Product()`, which means they are temporary `null`.

- As an example, SonataAdmin (https://sonata-project.org/bundles/admin/3-x/doc/getting_started/creating_an_admin.html) rely on database entity, to create, edit, show and list them. In the doc `@var` are not nullable, but this is kinda wrong, because adding a non-nullable typehint to the `getter` would crash the application during the creation of an entity.

So I would say that even if in a perfect world people would stop using entity DTO we're far far far from this.
It would be nice to be able to live in both world with these rules.

I personally use 
```
    /**
     * @var string|null
     *
     * @ORM\Column(type="string")
     */
    private $label;
```
since I don't have DTO object. And the doctrine rule is giving me an error then.

Changing to
```
    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $label;
```
could lead to more error, because I'm hiding the fact it can be `null`. That's especially why `psalm` is reporting every non-nullable non-initialized property as an error. Phpstan is supposed to help me to catch error not forcing me to rewrite all my code to use DTO or asking me to lie about the phpdoc and hide potentially bug.

And I'd like to avoid to ignore the error because, even in my case, it can catch mistakes as explained in the TLDR.

**Comment by patrick-vandy** [comment]
>I understand the "You should not use Entities as DTO" point of view. But this is very opinionated, here are different point of view:

@VincentLanglet I'm glad to hear I'm not the only one that feels this way. Honestly, I gave up on this issue when the last response I got was:

>With your coding style, these rules cannot perform any useful service for you, so just ignore them. Or make them help you understand how vulnerable application is, maybe baseline the existing errors, and try writing your new entities in a better way.

Clearly phpstan-doctrine has a pretty strong opinion about using entities as DTO and thinks we should "write entities in a better way". I'm not about to re-write my entire codebase and duplicate every property used in a form because a static analysis tool doesn't think I should follow the symfony documentation. My solution was to add this to `phpstan.neon.dist`

```
ignoreErrors:
    - '#type mapping mismatch: property can contain [a-zA-Z\\_]+\|null but database expects [a-zA-Z\\_]+#'
```

However, this wouldn't catch your scenario of `@var int|null` with `@ORM\Column(name="title", type="string", nullable=false)` which I hadn't thought of until reading your comment. It would be nice if phpstan-doctrine would at least move this specific error to higher level than 0.

**Comment by VincentLanglet** [comment]
> ```
> ignoreErrors:
>     - '#type mapping mismatch: property can contain [a-zA-Z\\_]+\|null but database expects [a-zA-Z\\_]+#'
> ```
> 
> However, this wouldn't catch your scenario of `@var int|null` with `@ORM\Column(name="title", type="string", nullable=false)` which I hadn't thought of until reading your comment. It would be nice if phpstan-doctrine would at least move this specific error to higher level than 0.

Yeah, I just did this in a similar way:
```
message: '#^Property .* type mapping mismatch\: property can contain .*\|null but database expects .*(?<!\|null)\.$#'
```
to also report `@var int|null` with `@ORM\Column(name="title", type="string", nullable=true)`.

But still, `@var int|null` with `@ORM\Column(name="title", type="string", nullable=false)` won't be reported.

**Comment by VincentLanglet** [comment]
> TLDR: Would it be possible to re-open the issue to introduce an option about this behavior @ondrejmirtes ?
> By default it forbid `null` for `non-nullable` property, but the option would allow it.
> 
> This avoid to ignore the error and will let people in my case to
> 
> * Not have error for `@var string|null` with `@ORM\Column(name="title", type="string", nullable=false)`
> * Still have error for `@var int|null` with `@ORM\Column(name="title", type="string", nullable=false)`
> 
> I just encounter this issue because I tried to enable the doctrines rules.
> 
> I understand the "You should not use Entities as DTO" point of view. But this is very opinionated, here are different point of view:
> 
> * Looking at the symfony/demo code https://github.com/symfony/demo/blob/main/src/Entity/Post.php getter have nullable typehint even if the database property is not nullable (and even if the class property has not null in the phpdoc).
> * Looking at the doctrine doc https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/tutorials/getting-started.html#adding-behavior-to-entities, it recommend DTO, but also have the following code
> 
> ```
> $product = new Product();
> $product->setName($newProductName);
> 
> $entityManager->persist($product);
> $entityManager->flush();
> ```
> 
> where `getName()` returns `null` before setting it.
> 
> * Looking at the symfony doc https://symfony.com/doc/current/doctrine.html#persisting-objects-to-the-database non-nullable property are set AFTER calling `new Product()`, which means they are temporary `null`.
> * As an example, SonataAdmin (https://sonata-project.org/bundles/admin/3-x/doc/getting_started/creating_an_admin.html) rely on database entity, to create, edit, show and list them. In the doc `@var` are not nullable, but this is kinda wrong, because adding a non-nullable typehint to the `getter` would crash the application during the creation of an entity.
> 
> So I would say that even if in a perfect world people would stop using entity DTO we're far far far from this.
> It would be nice to be able to live in both world with these rules.
> 
> I personally use
> 
> ```
>     /**
>      * @var string|null
>      *
>      * @ORM\Column(type="string")
>      */
>     private $label;
> ```
> 
> since I don't have DTO object. And the doctrine rule is giving me an error then.
> 
> Changing to
> 
> ```
>     /**
>      * @var string
>      *
>      * @ORM\Column(type="string")
>      */
>     private $label;
> ```
> 
> could lead to more error, because I'm hiding the fact it can be `null`. That's especially why `psalm` is reporting every non-nullable non-initialized property as an error. Phpstan is supposed to help me to catch error not forcing me to rewrite all my code to use DTO or asking me to lie about the phpdoc and hide potentially bug.
> 
> And I'd like to avoid to ignore the error because, even in my case, it can catch mistakes as explained in the TLDR.

Friendly ping @ondrejmirtes ; if I add a configuration for this, would it be accepted ?

**Comment by ondrejmirtes** [comment]
> if I add a configuration for this, would it be accepted ?

Yes

**Comment by VincentLanglet** [comment]
Done then https://github.com/phpstan/phpstan-doctrine/pull/208

**Comment by ondrejmirtes** [comment]
Solved by https://github.com/phpstan/phpstan-doctrine/pull/208
