### ISSUE TITLE
findOneBy does not validate entity object correctly

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-doctrine#201]
Hi there :wave: 

I have a similar issue than https://github.com/phpstan/phpstan-doctrine/issues/199 (I opened a new issue, as this one was closed and don't want to hijack :slightly_smiling_face: )

But as far as I can see, on my code it only affects the `findOneBy` method. I have configured a custom `repositoryClass` and a `objectManagerLoader`

I tried the solution with the `@extends` annotation, but still the same error. output from the dump methods:

> Dumped type: Shopware\Components\Model\ModelManager
Dumped type: Shopware\Models\Payment\Repository<Shopware\Models\Payment\Payment>
Dumped type: object|null

```
namespace Shopware\Models\Payment;

use Shopware\Components\Model\ModelRepository;

/**
 * Shopware Payment Model
 *
 * The repository builds the query to read the payments.
 * @extends \Shopware\Components\Model\ModelRepository<\Shopware\Models\Payment\Payment>
 */
class Repository extends ModelRepository
{}
```

Could you point me in the right direction here? I will happily provide a PR with a fix, when you could tell me where to start :blush:

**Comment by ondrejmirtes** [comment]
Hi,
how is `Shopware\Components\Model\ModelRepository` annotated with generics and what does it extend?

**Comment by mitelg** [comment]
Hi @ondrejmirtes 

thanks for the hint! It was not annotated, which is the problem :see_no_evil: 
I could fix it with the correct annotations in our custom repositories.

Thanks a lot again! 
Keep up your nice work :heart:

**Comment by ondrejmirtes** [comment]
BTW @mitelg what should have happened is that you should have got an error about `ModelRepository` extending a generic class and not specifying `@extends`. I guess you're either not on level 6 yet, or you've turned off `checkGenericClassInNonGenericObjectType` in your config file.

**Comment by mitelg** [comment]
hey @ondrejmirtes 

we are on level 8 and the option is on :blush: 
Unfortunately this error was not shown :man_shrugging:

**Comment by ondrejmirtes** [comment]
@mitelg I think it's worth investigating why you're not getting this error: https://phpstan.org/r/1ddfbc0a-2d4b-45eb-a7bf-90974892e269

**Comment by mitelg** [comment]
I will try to find out the reason :blush:
