### ISSUE TITLE
Implement a rule that prevents final constructors in Doctrine Entities

### ISSUE THREAD

**Issue by gnutix** [phpstan/phpstan-doctrine#202]
Hello there,

I'm having quite a hard time getting my head around this : [final methods in Doctrine Entities](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/architecture.html#entities). There's [a PR](https://github.com/phpstan/phpstan-doctrine/pull/143) that added a check that Entities cannot be final (the class itself), but [a comment](https://github.com/phpstan/phpstan-doctrine/pull/143#issuecomment-698225313) from the author said he doesn't want to add checks for final methods.

However, from what I can see in my Doctrine proxied classes in var/cache in production, *all* methods of the class is inherited/overridden in proxies. So it just cannot work with a final method, whichever it is.

Why hasn't this check been added then ?

I'm curious about your insights. Thanks!
gnutix

**Comment by ondrejmirtes** [comment]
Ask the author :) /cc @enumag

**Comment by enumag** [comment]
Yeah I have a case where I don't want the proxy to override my method. Granted it's a bit of an edge-case so adding such rule to PHPStan makes sense but please make it separate from the rule I added.

**Comment by gnutix** [comment]
@enumag But how could it even work in your app ? When I added `final` to a private constructor of an entity, PHP just broke saying "cannot override final method" (in the Doctrine Proxy). How can you have a final method in an entity then, and not having Doctrine's proxy to break ? :thinking:

**Comment by enumag** [comment]
There is a misunderstanding... the method is not the constructor.

**Comment by gnutix** [comment]
Okay, so you agree that there should be a rule (that is always loaded) guarding against final constructors for Doctrine Entities (not all methods) then ?

**Comment by enumag** [comment]
Sure.
