### ISSUE TITLE
Database can contain int but property expects int<1, max>.  

### ISSUE THREAD

**Issue by simPod** [phpstan/phpstan-doctrine#207]
It seems the extension does not support int ranges but I have not found out why. I checked that IntegerRangeType is a subclass of IntegerType.

Any idea? Thanks!

```php
	/**
	 * @var positive-int
	 * @ORM\Column(type="integer")
	 */
	private $positiveInteger;
```

> Property A::$positiveInteger type mapping mismatch: database can contain int but property expects int<1, max>.

**Comment by ondrejmirtes** [comment]
Same thing as: https://github.com/phpstan/phpstan-doctrine/issues/204
