### ISSUE TITLE
Repository type not matched when set to a property

### ISSUE THREAD

**Issue by Soullivaneuh** [phpstan/phpstan-doctrine#21]
In a nutshell, this PHP class:

```php
use Doctrine\ORM\Decorator\EntityManagerDecorator;
use PowerDNSBundle\Doctrine\ORM\PowerDNSEntityManager;
use PowerDNSBundle\Entity\PowerDNSDomain;

class DnsManager extends EntityManagerDecorator
{
    /**
     * @var ObjectRepository
     */
    private $domainRepository;

    public function __construct(PowerDNSEntityManager $wrapped)
    {
        parent::__construct($wrapped);

        $this->domainRepository = $this->getRepository(PowerDNSDomain::class);
    }

    public function addDomainIfNotExists($name, User $user, $ipV4 = null, $ipV6 = null, $checkDNS = true)
    {
        $nameCanonical = \idn_to_ascii($name);
        $domain = $this->domainRepository->findOneBy(['name' => $nameCanonical]);

        if (!$domain) {
            $domain = new PowerDNSDomain();
            $domain->setName($name);
            $domain->setOwnerId($user->getId());
            $this->saveDomain($domain, $ipV4, $ipV6, $checkDNS);
        }

        return $domain;
    }
}
```

Produces:

```
 ------ ---------------------------------------------------------------------- 
  Line   src/AppBundle/Manager/DnsManager.php                                  
 ------ ---------------------------------------------------------------------- 
  170    Method AppBundle\Manager\DnsManager::addDomainIfNotExists() should    
         return PowerDNSBundle\Entity\PowerDNSDomain but returns object.       
```

Replacing the line by `$domain = $this->getRepository(PowerDNSDomain::class)->findOneBy(['name' => $nameCanonical]);` directly "solve" the issue.

It seems the property assignation of repositories is not handled by the extension.

**Comment by ondrejmirtes** [comment]
This is currently not possible because there's no way how to write a `@var` above a property that would tell that there's `EntityRepository<PowerDNSDomain>`. That would require a lot of coordinated effort across `phpstan/phpdoc-parser` and `phpstan/phpstan` which is planned for the future but not on the immediate roadmap. cc @JanTvrdik thoughts?

**Comment by JanTvrdik** [comment]
Well, phpstan/phpstan uses DI, so in theory extensions can extend a LOT more stuff, than is officially documented, i.e. `phpstan/phpstan-doctrine` can decorate the `TypeNodeResolver` service to resolve `EntityRepository<PowerDNSDomain>` to `EntityRepositoryType `. Not changes to `phpstan/phpdoc-parser` are required.

**Comment by ondrejmirtes** [comment]
That's nice to know! I don't consider TypeNodeResolver as a public API with any BC incentives so I'd rather have an official extension point, but this can be used meanwhile...

**Comment by lcobucci** [comment]
@Soullivaneuh @ondrejmirtes it looks like this has already been fixed in newer versions of PHPStan (as proven by #37).

**Comment by ondrejmirtes** [comment]
This is now supported, but you have to write `@var ObjectRepository<PowerDNSDomain>`.
