### ISSUE TITLE
Error when adding rules.neon

### ISSUE THREAD

**Issue by mkoske** [phpstan/phpstan-doctrine#210]
When I add this:

```neon
includes:
    - app/vendor/phpstan/phpstan-doctrine/rules.neon
    - app/vendor/phpstan/phpstan-doctrine/extension.neon
```

to my `phpstan.neon`, I get this:

`Service of type PHPStan\Rules\Doctrine\ORM\EntityColumnRule: Unable to pass specified arguments to __construct().`

But if I remove `rules.neon`, there's no error. Why would it be?

I have this:

```
        "phpstan/phpstan": "^0.12.98",
        "phpstan/phpstan-doctrine": "^0.12.44"
```

in my `composer.json`

**Comment by ondrejmirtes** [comment]
Hi, this can only happen if there multiple phpstan-doctrine versions at play. You're probably combining installing PHPStan locally in your project but probably running it from global Composer installation, or something like that.

You should install PHPStan in your project and run it from the same project.

**Comment by mkoske** [comment]
Hi, thanks! It was exactly that. I removed global version of phpstan-doctrine and the error was gone. But now I got another error: 

```
Service '0305': Class or interface 'PHPStan\Type\Doctrine\DescriptorRegistry' not found.
```

**Comment by ondrejmirtes** [comment]
There's still something weird about your installation...

**Comment by mkoske** [comment]
Hm, using local phpstan instead of global fixed this latter issue. I had both global and local installed because I couldn't get VSCode phpstan extension to work with local version (I have custom app structure which doesn't seem to work with that extension).

**Comment by mkoske** [comment]
Issue was duplicate installation (both local and global). Closing this.
