### ISSUE TITLE
PHP Warning: Module already loaded

### ISSUE THREAD

**Issue by mkoske** [phpstan/phpstan-doctrine#212]
Hello! When I use phpstan-doctrine, I get this error for many PHP modules:

```
PHP Warning:  Module '<a module name here, e.g. zip>' already loaded in Unknown on line 0
```

Why is this happening? With just phpstan, without phpstan-doctrine extension, works just fine.

**Comment by ondrejmirtes** [comment]
No idea, this should not be happening. It's an issue with your PHP installation. Do you have Xdebug enabled?

**Comment by mkoske** [comment]
Yea, it seems to be enabled

**Comment by mkoske** [comment]
Hm, removing Xdebug (I don't need it) helped. Thanks!
