### ISSUE TITLE
Type mismatch?

### ISSUE THREAD

**Issue by mkoske** [phpstan/phpstan-doctrine#213]
Hello!

I get this error:

`Property MyEntity::$id type mapping mismatch: database can contain string but property expects int.`

But the database column _is_ (big)int. So why this warning?

This is the line from the `describe <mytable>` command:

`| id              | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |`

Also, in the Doctrine YAML mapping file, id is the identity with type of unsigned bigint.

**Comment by ondrejmirtes** [comment]
From Doctrine manual (https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/basic-mapping.html):

>  bigint: Type that maps a database BIGINT to a PHP string.

**Comment by mkoske** [comment]
Oh, that explains some other issue too (not related to phpstan). Thanks!

**Comment by mkoske** [comment]
Hello again, @ondrejmirtes!

I saw this again and I have to ask that isn't this just opposite what the warning message states? Database cannot contain string, it is bigint as it is defined in create database statement. It is Doctrine that maps it to PHP string in the code. Right?

**Comment by ondrejmirtes** [comment]
You need to type the property as string, because that reflects the reality.

**Comment by mkoske** [comment]
Yea, I see what you mean, but the error message states that _"database can contain string"_ and that's not the case. It's bit confusing message.
