### ISSUE TITLE
Infering the result type of a Query instance

### ISSUE THREAD

**Issue by arnaud-lb** [phpstan/phpstan-doctrine#221]
It may be possible to infer the return type of execute(), getResult(), etc on Query instances when the query string is known statically.

This could be implemented like this:

- Override the Query and AbstractQuery classes so that they have a type parameter, representing the type of their results (e.g. a `Query` returning `User` objects would be a `Query<User>`)
- Add a return type extension for EntityManagerInterface::createQuery(), to infer the result type from the query string, and so that we can tel that createQuery() returns a `Query<something>`

The ResultSetMapper of a Query provides enough info to infer the result type in the most simple cases (e.g. `SELECT u FROM User`). This would already be super useful. Other cases might require a custom SqlWalker because the ResultSetMapper doesn't provide any information on nullability, for example.

**Comment by noemi-salaun** [comment]
I think the type can also be infered with QueryBuilder, like in this case

```php
    /**
     * @return VariableModifier[]
     */
    public function getAll(): array
    {
        return $this->getEntityManager()->getRepository(VariableModifier::class)
            ->createQueryBuilder('modifier')
            ->getQuery()
            ->getResult();
    }
```

**Comment by arnaud-lb** [comment]
Here is a more advanced branch that implements type inference for most queries: https://github.com/phpstan/phpstan-doctrine/compare/master...arnaud-lb:query-result-type-2?expand=1

It will properly infer the result type of any query, including queries with scalar results, joins or left joins, aggregations, functions, and all kinds of expressions.

There are a few things I left for later: sub queries, identity(), size(). These things will cause some parts of the query result to be mixed, so there will be no false typing.

I may eventually submit this in two PRs:
- Generic Query stub + infering the dynamic return type extension for EntityManager::createQuery()
- Dynamic return type extension for Query::getResult / execute / etc

WDYT ?

**Comment by enumag** [comment]
@arnaud-lb Sounds great. For now let's focus on the most common cases. Indeed it makes no sense to delay this feature for sub queries and such. Please make a PR where we can discuss the details. You can make it as a draft if unsure about some things.

**Comment by arnaud-lb** [comment]
Thanks @enumag. I opened a PR at https://github.com/phpstan/phpstan-doctrine/pull/232

**Comment by ondrejmirtes** [comment]
https://github.com/phpstan/phpstan-doctrine/pull/232 merged and released as phpstan-doctrine 1.2.1 :)

**Comment by fliespl** [comment]
@ondrejmirtes It works fine with basic queries, but once: setLockMode is attached to getQuery() it loses context and reports error.

**Comment by ondrejmirtes** [comment]
@fliespl Feel free to open a new bug report with more details about it.
