### ISSUE TITLE
[RFC] Support by default that Gedmo properties are always written

### ISSUE THREAD

**Issue by yguedidi** [phpstan/phpstan-doctrine#231]
From PHPStan 1.0 there is a better [Detecting Unused Private Properties, Methods, and Constants](https://phpstan.org/blog/detecting-unused-private-properties-methods-constants) enabled.

Since then, many entity properties get reported as

> Property $foo is never written, only read.

In my case, all of them were properties using `Timestampable` from Doctrine Extensions, without setter/getter.

I suggest to include by default with phpstan-doctrine a PHPStan extension that marks properties using `Timestampable` as always written, following [the official PHPStan instructions](https://phpstan.org/blog/detecting-unused-private-properties-methods-constants#what-if-my-code-is-%E2%80%9Cspecial%E2%80%9D%3F)

What do you think?

---

Here a basic example of that extension that work in my case:

```php
<?php

namespace App\PHPStan;

use PHPStan\Reflection\PropertyReflection;
use PHPStan\Rules\Properties\ReadWritePropertiesExtension;

final class PropertiesExtension implements ReadWritePropertiesExtension
{
    public function isAlwaysRead(PropertyReflection $property, string $propertyName): bool
    {
        return false;
    }

    public function isAlwaysWritten(PropertyReflection $property, string $propertyName): bool
    {
        return str_contains($property->getDocComment(), '@Gedmo\Timestampable');
    }

    public function isInitialized(PropertyReflection $property, string $propertyName): bool
    {
        return false;
    }
}
```

**Comment by ondrejmirtes** [comment]
Hi, it doesn't even need any extension code written. There are two undocumented parameters that serve the same purpose: https://github.com/phpstan/phpstan-src/blob/9488d34977f5e63728b4f182d17ccbfc426d1b4d/conf/config.neon#L70-L71

Example usage:

```neon
parameters:
	propertyAlwaysWrittenTags:
		- '@@set'
	propertyAlwaysReadTags:
		- '@@get'
```

The `@` needs to be doubled so that nette/di understands it's not a service object reference.

Please send a PR here to phpstan-doctrine with this configuration.

**Comment by stof** [comment]
@ondrejmirtes given that `@Gedmo\Timestampable` is a doctrine annotation in that case, and that the `@Gedmo` part could be anything (and even absent) depending on how you write your use statements, would that work as well ?

Even better would be to mark all mapped properties using a `Gedmo` annotation as being always written, not only the ones using `Timestampable`

**Comment by ondrejmirtes** [comment]
Yeah, in that case we need an extension that properly reads the PHPDoc.

**Comment by stof** [comment]
Given that gedmo/doctrine-extensions is an extension of Doctrine (and a commonly used one), would that be accepted in phpstan-doctrine directly ? Or do you prefer it to live in a separate package ?

**Comment by ondrejmirtes** [comment]
If Gedmo is always used as part of Doctrine, it makes sense to have it here as well.
