### ISSUE TITLE
[RFC] remove generic stubs in favor of the upstream generic annotations

### ISSUE THREAD

**Issue by stof** [phpstan/phpstan-doctrine#237]
Recent doctrine versions (covering all the maintained IIRC) are shipping with generic annotations in their source code (using `@psalm-*` annotations but phpstan will read them).
I suggest removing the generic stubs from this extension in favor of the Doctrine code, which will reduce maintenance work (as having stubs that are out of sync with the official generic types would likely cause weird issues)

**Comment by ondrejmirtes** [comment]
Hi, until someone still uses old Doctrine versions without annotations, the stubs need to be here :)

**Comment by stof** [comment]
@ondrejmirtes the issue is that those stubs are winning over official generic annotations, even when they are out of sync with official ones (which the produces a WTF moment, as the IDE will show the official ones).

Maybe those stubs should be registered only for old versions then.

**Comment by ondrejmirtes** [comment]
Please send a PR to update the out of sync stubs, thanks.
