### ISSUE TITLE
Using a custom QueryBuilder object

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-doctrine#243]
hey there :wave: 

in our [project](https://github.com/shopware/shopware) we have a custom `QueryBuilder` which extends the original one of Doctrine, to add some features. It is created in the `ModelManager::createQueryBuilder()` which extends from the original `EntityManager`.

Unfortunately if now `ModelManager::createQueryBuilder()` is called, the result is interpreted as `Doctrine\ORM\QueryBuilder`.

I tried the following stub files to teach PHPStan the correct return value, but with no success. 

<details>
<summary>EntityRepository</summary>

```
<?php

namespace Doctrine\ORM;

use Doctrine\Common\Collections\Selectable;
use Doctrine\Persistence\ObjectRepository;
use Shopware\Components\Model\ModelManager;

/**
 * @template TEntityClass of object
 * @implements ObjectRepository<TEntityClass>
 * @implements Selectable<int, TEntityClass>
 */
class EntityRepository implements ObjectRepository, Selectable
{
    protected function getEntityManager(): ModelManager;
}
```

</details>

<details>
<summary>ModelManager</summary>

```
<?php

namespace Shopware\Components\Model;

use Doctrine\ORM\EntityManager;

class ModelManager extends EntityManager
{
    public function createQueryBuilder(): QueryBuilder;
}
```
</details>

<details>
<summary>QueryBuilder</summary>

```
<?php

namespace Shopware\Components\Model;

use Doctrine\ORM\QueryBuilder as BaseQueryBuilder;

class QueryBuilder extends BaseQueryBuilder
{
}
```
</details>

<details>
<summary>The Doctrine plugin should also be correctly configured:</summary>

```
    doctrine:
        repositoryClass: Shopware\Components\Model\ModelRepository
        objectManagerLoader: tests/phpstan-doctrine-model-manager.php
```
`tests/phpstan-doctrine-model-manager.php`
```
<?php

declare(strict_types=1);

use Shopware\Components\Model\ModelManager;
use Shopware\Kernel;

require __DIR__ . '/../autoload.php';

$kernel = new Kernel('production', false);
$kernel->boot();

$modelManager = $kernel->getContainer()->get('models');
\assert($modelManager instanceof ModelManager);

return $modelManager;
```
</details>

[QueryBuilder](https://github.com/shopware/shopware/blob/5.7/engine/Shopware/Components/Model/QueryBuilder.php)
[ModelManager](https://github.com/shopware/shopware/blob/5.7/engine/Shopware/Components/Model/ModelManager.php#L48)
[ModelManager::createQueryBuilder](https://github.com/shopware/shopware/blob/5.7/engine/Shopware/Components/Model/ModelManager.php#L163)

Do I miss a stub or a config? Can I somehow debug why the type of `ModelManager::createQueryBuilder()` is interfered like that?

Thanks in advance and have a nice day :wave:

**Comment by ondrejmirtes** [comment]
Hi, we’re doing the same thing at Slevomat, we’re overriding this setting with our custom class: https://github.com/phpstan/phpstan-doctrine/blob/5fa8fefdf7d3b41ada096c0271250e2faf1d6adc/extension.neon#L6

**Comment by mitelg** [comment]
oh wow, that was easy :sweat_smile: 

thank you very much @ondrejmirtes 
very helpful as always :tada:
