### ISSUE TITLE
Add support for enums on mapped object properties

### ISSUE THREAD

**Issue by mbabker** [phpstan/phpstan-doctrine#246]
ORM 2.11 added support for PHP 8.1 enums (and there is an open feature request for the MongoDB ODM for a similar addition).  It would be nice if PHPStan could support these at some point down the line as well.  Right now, you get type mapping mismatch errors when using them:

```sh
 ------ -------------------------------------------------------------------------------------------------------------------------
  Line   Entity/Event.php
 ------ -------------------------------------------------------------------------------------------------------------------------
  xx     Property App\Entity\Event::$type type mapping mismatch: database can contain string but property expects App\EventType.
  xx     Property App\Entity\Event::$type type mapping mismatch: property can contain App\EventType but database expects string.
```

**Comment by ondrejmirtes** [comment]
Please post a piece of code that reports these errors.

**Comment by mbabker** [comment]
https://github.com/mbabker/phpstan-doctrine-enum has the minimal code to show this.

**Comment by ondrejmirtes** [comment]
Implemented: https://github.com/phpstan/phpstan-doctrine/commit/820606a0e6116c4566871e44e22949815a3e36a8

And released: https://github.com/phpstan/phpstan-doctrine/releases/tag/1.0.3

Feel free to sponsor PHPStan ;) https://github.com/sponsors/ondrejmirtes

Or get PHPStan Pro: https://phpstan.org/blog/introducing-phpstan-pro
