### ISSUE TITLE
\Entity\ExifData::$id is never written, only read.  

### ISSUE THREAD

**Issue by carstep** [phpstan/phpstan-doctrine#249]
hi there,

I recently updated my code and phpstan to support php8.1 and I came across new this errors after updating from 0.12.99 to 1.4.2, and phpstan-doctrine to 1.1.1. 
It suggested me also to visit https://phpstan.org/developing-extensions/always-read-written-properties which involved install this package.

According to the description it handled autoincremented values by self and wont trigger such messages.

I tried to overcome this message in the subject of this issue by declaring setId as private (that is will not be reached by no means) the message still not disappeared. 

My final solution was as follow, but its inconvenient as this function should not be even present:
```php
    public function setId(int $id): void
    {
        $this->id = $id;
        throw new BadMethodCallException();
    }
```

How can I deleted this function not to present me such error messages, and what happens if I switch to yaml configuration of doctrine entities?

PS: Doctrine complete entity headers
```php
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class ExifData
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @var int
     */
    private $id;
    ....
```

**Comment by ondrejmirtes** [comment]
Please post the relevant code of your entity - the $id column definition. Also make sure you've configured the object manager loader from the README.

**Comment by carstep** [comment]
REAMDE suggest some manual setting u mean that?
updated the original post

I`am using this
```
 php -d memory_limit=-1 vendor/bin/phpstan.phar analyze --level 6 src
```

**Comment by ondrejmirtes** [comment]
Follow the README regarding the objectManagerLoader: https://github.com/phpstan/phpstan-doctrine#configuration

**Comment by carstep** [comment]
OK, many thanks for support, i followed object-manager setup, worked quiet well, and even with yaml entity configuration seems to work.
The readme suggest only DQL improvements, i would add maybe annotation or yaml configuration related Doctrine setting should require this setup as well.
