### ISSUE TITLE
How to install phpstan-doctrine if PHPStan is not installed through Composer?

### ISSUE THREAD

**Issue by hkdobrev** [phpstan/phpstan-doctrine#25]
If I'm using Phive or the PHPStan shim to install PHPStan, how do I install `phpstan-doctrine` which doesn't seem to provide a PHAR and still requires `phpstan/phpstan` when installed through Composer?

**Comment by ondrejmirtes** [comment]
Hi, on 0.9, `phpstan/phpstan-shim` `replace`s `phpstan/phpstan` so you can combine shim with PHPStan extensions and `phpstan/phpstan` itself does not get installed anymore.
