### ISSUE TITLE
The default objectManagerLoader doesn't work when the entity has an embedded field.

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-doctrine#254]
Since https://github.com/phpstan/phpstan-doctrine/pull/253, the metadata is resolved without the need of an objectManagerLoader.

It works well, but I have the following issue:
```
$this->getEntityManager()->getRepository(Expedition::class)->getListOrders($context, $date);
```
report an error 
```
Call to an undefined method Doctrine\ORM\EntityRepository<App\Entity\Expedition>::getListOrders().  
```

`getRepository` is considered as an `EntityRepository` instead of `ExpeditionRepository`.
Seems like that as soon as I remove the field 
```
/**
 * @ORM\Embedded(class="App\Entity\Embeddable\Slot")
 */
private ?Slot $slot = null;
```
from the Expedition entity, it works well.

**Comment by VincentLanglet** [comment]
For my Expedition entity this line https://github.com/phpstan/phpstan-doctrine/blob/master/src/Type/Doctrine/ObjectMetadataResolver.php#L181 returns null. (but not for others entities)

After some dump, I discovered I ends here https://github.com/phpstan/phpstan-doctrine/blob/master/src/Type/Doctrine/ObjectMetadataResolver.php#L120

With the exception message
```
No identifier/primary key specified for Entity "App\Entity\Embeddable\Slot". Every Entity must have an identifier/primary key.
```
But there is no need for identifier https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/tutorials/embeddables.html

I think there is something to improve in the `PHPStan\Doctrine\Mapping\ClassMetadataFactory`.

**Comment by VincentLanglet** [comment]
Adding 
```
	protected function validateRuntimeMetadata($class, $parent)
	{
		return;
	}
```
to the Phpstan metadatafactory solve the issue.

Would you agree with this @ondrejmirtes ?

**Comment by ondrejmirtes** [comment]
That just seems like a workaround.

Does this work when you provide `objectManagerLoader`? Can you check why?

**Comment by VincentLanglet** [comment]
> Does this work when you provide `objectManagerLoader`? Can you check why?

I use both ORM and ODM on my project.
I used my own fork with https://github.com/phpstan/phpstan-doctrine/pull/218 with this objectManagerLoader https://github.com/phpstan/phpstan-doctrine/pull/218/files#diff-7be597212047526284ecdf31e9ea0e3cd38415a178b2ebb71af7a7204f388de9 and it was working.

To debug this, I simply run 
```
public function __construct(EntityManagerInterface $entityManager)
    {
        $entityManager->getMetadataFactory()->getMetadataFor(Expedition::class);

        (new \PHPStan\Doctrine\Mapping\ClassMetadataFactory())->getMetadataFor(Expedition::class);

        parent::__construct();
    }
```
in my symfony project.

The first `getMetadataFor` work, but the second doesn't.

I ended up in the `Doctrine\ORM\Mapping\ClassMetadataFactory::doLoadMetadata` which call `validateRuntimeMetadata`, in which the call `$class->validateIdentifier()` is made.
```
    public function validateIdentifier()
    {
        if ($this->isMappedSuperclass || $this->isEmbeddedClass) {
            return;
        }
        // do things
```

When the call is made by the phpstan factory, `$this->isEmbeddedClass` is false (but it's true with the doctrine factory).

So I find out that the `Doctrine\ORM\Mapping\Driver\AnnotationDriver::loadMetadataForClass` is supposed to do the job.
It's called with Expedition and Slot for Doctrine.
It's only called with Expedition for Phpstan.

**Comment by VincentLanglet** [comment]
Ok, so I found why.

Everything is done by the line 
```
$this->driver->loadMetadataForClass($class->getName(), $class);
```
here: https://github.com/doctrine/orm/blob/2.11.x/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L133

In the MappingDriverChain, the code is
```
	public function loadMetadataForClass($className, ClassMetadata $metadata): void
	{
		foreach ($this->drivers as $driver) {
			if ($driver->isTransient($className)) {
				continue;
			}

			$driver->loadMetadataForClass($className, $metadata);
			return;
		}
	}
```
and `$driver->isTransient($className)` return true for embeddable entities.

Doctrine is doing `$driver->loadMetadataForClass($className, $metadata)` without any transient check.

I tried changing the code to
```
	public function loadMetadataForClass($className, ClassMetadata $metadata): void
	{
		foreach ($this->drivers as $driver) {
			$driver->loadMetadataForClass($className, $metadata);
		}
	}
```
but it doesn't work, I get another error. But changing it to
```
	public function loadMetadataForClass($className, ClassMetadata $metadata): void
	{
		foreach ($this->drivers as $driver) {
			$driver->loadMetadataForClass($className, $metadata);
                         return;
		}
	}
```
solve the issue for me, because I use Annotation IMHO ; it will just break for people relying on Attribute since the driver won't be use.

**Comment by ondrejmirtes** [comment]
This should work: https://github.com/phpstan/phpstan-doctrine/commit/5fa8fefdf7d3b41ada096c0271250e2faf1d6adc

Thanks.

**Comment by VincentLanglet** [comment]
> This should work: [5fa8fef](https://github.com/phpstan/phpstan-doctrine/commit/5fa8fefdf7d3b41ada096c0271250e2faf1d6adc)
> 
> Thanks.

Indeed, it works for me.
