### ISSUE TITLE
Wrong type inference for QueryBuilder::update and QueryBuilder::delete.

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-doctrine#259]
The following code
```
$result = $this->getEntityManager()
            ->getRepository(ProductCrossSell::class)
            ->createQueryBuilder('pcs')
            ->where('pcs.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->delete()
            ->getQuery()
            ->getResult();

\PHPStan\dumpType($result);
```
Is considering `$result` as an array. But it's an int: the number of deleted elements. Same with `update()`

It was introduce by https://github.com/phpstan/phpstan-doctrine/pull/232 cc @arnaud-lb

**Comment by arnaud-lb** [comment]
Hi @VincentLanglet 

I believe that there are two distinct issues here. The first one is that

```
$result = $this->getEntityManager()
            ->getRepository(ProductCrossSell::class)
            ->createQueryBuilder('pcs')
            ->where('pcs.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->delete()
            ->getQuery()
```

may be `Query<mixed>`. Could you confirm ?

If that's the case, there is a second problem:  the type of `Query<mixed>::getResult()` should not be `array` because the query may be an INSERT or DELETE query.

**Comment by VincentLanglet** [comment]
> may be `Query<mixed>`. Could you confirm ?

Indeed `Dumped type: Doctrine\ORM\Query<mixed>`

**Comment by arnaud-lb** [comment]
Thank you.

I'm fixing the second issue in #260.

I'm not sure about the cause of the first issue. What is the type of `->getRepository(ProductCrossSell::class)` ? Could you confirm that the query is valid ?

**Comment by VincentLanglet** [comment]
> I'm not sure about the cause of the first issue. What is the type of `->getRepository(ProductCrossSell::class)` ?

```
Dumped type: App\Repository\ProductCrossSellRepository<App\Entity\ProductCrossSell>  
```

> Could you confirm that the query is valid ?

Yes, it's just a DELETE with a WHERE condition on ids.
