### ISSUE TITLE
Support for ODM

### ISSUE THREAD

**Issue by josefsabl** [phpstan/phpstan-doctrine#26]
Is ODM supported? I guess not. Do you plan to add the support?

**Comment by ondrejmirtes** [comment]
What exactly are you missing and how would you imagine the support to look like? I'm not familiar with ODM so I don't know if it's enough to make the referenced interfaces more general or if there's some completely new area to implement.

**Comment by ondrejmirtes** [comment]
I believe ODM is now supported.
