### ISSUE TITLE
Add option to ignore annotations

### ISSUE THREAD

**Issue by Khartir** [phpstan/phpstan-doctrine#261]
With the new usage of the Doctrine AnnotationReader phpstan fails if there are unknown annotations in a class. Doctrine offers `AnnotationReader::addGlobalIgnoredNamespace` and `AnnotationReader::addGlobalIgnoredName` to ignore specific annotations. Would you be interested in a PR that adds options to configure the AnnotationReader to ignore specific annotations?

**Comment by ondrejmirtes** [comment]
Right now I'm investigating why `Doctrine\Common\Annotations\DocParser::$ignoreNotImportedAnnotations` is `true` when using objectManagerLoader but it's `false` when using the new ClassMetadataFactory: https://github.com/phpstan/phpstan-doctrine/blob/master/src/Doctrine/Mapping/ClassMetadataFactory.php

Perhaps you can help me with that? Thank you.

**Comment by Khartir** [comment]
I just startet looking into the objectManagerLoader. In my project it is not `true` when using the loader, however the errors disappear because we have a CompilerPass that adds those ignored names. When removing that compiler pass phpstan once again crashes due to missing annotations. However, this is an older project, so maybe in newer projects symfony adds this in compiler pass somewhere?

**Comment by ondrejmirtes** [comment]
Fixes released as phpstan-doctrine 1.2.4: https://github.com/phpstan/phpstan-doctrine/releases/tag/1.2.4

Please test it :)

**Comment by Khartir** [comment]
Works fine, thank you.
