### ISSUE TITLE
Type inference for custom types results to mixed

### ISSUE THREAD

**Issue by janedbal** [phpstan/phpstan-doctrine#275]
Is there any chance this will be supported? We use custom types a lot and therefore a lot of our deduced result shapes contains mixed type.

```php
class SomeEntity {
    /**
     * @ORM\Column(type=ContainerTypeType::NAME, nullable=true)
     */
    private ?ContainerType $containerType;
}
```
Here, `ContainerTypeType` extends `Doctrine\DBAL\Types\StringType` and converts the string to ContainerType in convertToPHPValue (+ reverse in convertToDatabaseValue).

/cc @arnaud-lb

**Comment by arnaud-lb** [comment]
Hi @janedbal 

I think that if you register a custom type descriptor for your custom type, as described [here](https://github.com/phpstan/phpstan-doctrine#registering-type-descriptors), this will work.

We use `getWritableToPropertyType()` to determine the field type (when the field is selected like in `SELECT e.containerType FROM Entity e`), and `getDatabaseInternalType()` to determine the raw type (when the field is used in an expression like in `SELECT FUNCTION(e.containerType) FROM Entity e`).

It could also be possible to support custom types out of the box as long as their `convertToPHPValue()` implementation have a return type. This would be enough information to infer at least the type of field selections.

**Comment by janedbal** [comment]
Missed that, sorry, it works fine, thank you!
