### ISSUE TITLE
Type infering not working for getSingleScalarResult nor getSingleResult(Query::HYDRATE_SINGLE_SCALAR)

### ISSUE THREAD

**Issue by janedbal** [phpstan/phpstan-doctrine#276]
> getOneOrNullResult() and getSingleResult() are supported, but only when explicitly specifying the hydration mode

It was stated [here](https://github.com/phpstan/phpstan-doctrine/pull/232#issuecomment-1015686749) that this should be supported, but it seems like the inferred type is mixed. Or did I misunderstood?

```php
$query = $em->createQueryBuilder()
	->addSelect('m.id')
	->from(Many::class, 'm');

assertType(
	'int',
	$query->getQuery()
		// ->getSingleScalarResult()
		->getSingleResult(Query::HYDRATE_SINGLE_SCALAR)
);
```

Method **getSingleColumnResult** seems to be not supported as well, is that correct?

cc @arnaud-lb

**Comment by arnaud-lb** [comment]
Hi @janedbal 

> getOneOrNullResult() and getSingleResult() are supported, but only when explicitly specifying the hydration mode

Here I meant when explicitly specifying the hydration mode to `HYDRATE_OBJECT`

> Method getSingleColumnResult seems to be not supported as well, is that correct?

Yes, getSingleColumnResult is not supported currently. I don't think that it can be supported until we support multiple hydration modes.

**Comment by janedbal** [comment]
Thanks for response, do you plan to add support for more hydration modes?

**Comment by janedbal** [comment]
[Assuming not](https://github.com/phpstan/phpstan-doctrine/issues/269#issuecomment-1023165944). Closing.
