### ISSUE TITLE
Connection to the database is triggered

### ISSUE THREAD

**Issue by gboutte** [phpstan/phpstan-doctrine#292]
I'm not sure i should post here, let me know if it's not the right place.

I am using `phpstan` 1.4 and `phpstan-doctrine` 1.2.

When i run phpstan ` vendor/bin/phpstan analyze` it appears that phpstan is trying to connect to the database, but it's not accessible.
```
Internal error: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "postgres_db" to address: nodename nor servname provided, or not known
```

I know that it's when there is a getRepository because when i comment it i don't have the error.

```php
$this->userRepository = $this->entityManager->getRepository(User::class);
```

I ran phpstan with the `--debug` flag, i have 3 lines that are about phpstan-doctrine, the rest is inside phpstan files or doctrine files.

```
// Doctrine part

#12 /Users/gboutte/myproject/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(131): Doctrine\ORM\EntityManager->getClassMetadata('App\\Entities\\Us...')
#13 /Users/gboutte/myproject/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/GetRepositoryDynamicReturnTypeExtension.php(153): PHPStan\Type\Doctrine\ObjectMetadataResolver->getClassMetadata('App\\Entities\\Us...')
#14 /Users/gboutte/myproject/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/GetRepositoryDynamicReturnTypeExtension.php(112): PHPStan\Type\Doctrine\GetRepositoryDynamicReturnTypeExtension->getRepositoryClass('App\\Entities\\Us...', 'Doctrine\\ORM\\En...')

// Phpstan part
```

If i look at `src/Type/Doctrine/ObjectMetadataResolver.php` line 131 
https://github.com/phpstan/phpstan-doctrine/blob/5a5454cf8d7916b39c6423beed592fb141743937/src/Type/Doctrine/ObjectMetadataResolver.php#L122-L135

the `$metadata = $objectManager->getClassMetadata($className);` is triggering the connection.
I tried to remove the condition and always do the if part:
```php

$metadataFactory = $this->getMetadataFactory();
if ($metadataFactory === null) {
	return null;
}

$metadata = $metadataFactory->getMetadataFor($className);
```

With that changes i don't have the error anymore, but i don't know exactly what was the purpose of that line.

Does phpstan need to connect to the database ? What do you think about this ?

**Comment by jlherren** [comment]
Hi! I might be completely wrong here, but it's worth a shot.

I had a similar issue with Doctrine connecting to MariaDB, when I wasn't doing any queries at all. The problem is that Doctrine needs to know what version of the DB server it is working with in order to instantiate the correct `AbstractPlatform` implementation, of which there are several available for the same DB vendor (e.g. `PostgreSQL94Platform` or `PostgreSQL100Platform` for postgres, and similarly for other DB drivers). To auto-detect this information, it will simply connect to the DB and query the version.

To turn off this auto-detection, you can specify this information in advance, like so:

    $params = [
        'host' => 'localhost',
        'user' => 'dbuser',
        ...
        'serverVersion' => '14.2',
    ];

**Comment by gboutte** [comment]
@jlherren You were right, it was caused by the serverVersion, I added it and I no longer have the error.

Since i'm using an url I added it on my url:
```
DATABASE_URL=postgres://user:password@database_ip/database?serverVersion=14.2
```

```php
$params = [
    'url' => $database_url,
];
```
