### ISSUE TITLE
Constructor new ArrayCollection. Property $things (Collection<int, Thing>) does not accept ArrayCollection<(int|string), mixed>

### ISSUE THREAD

**Issue by philrennie** [phpstan/phpstan-doctrine#296]
I'm initialising a property with a new ArrayCollection in my entity constructor, and phpstan is telling me

Property TestEntity::$things (Doctrine\Common\Collections\Collection<int, EntityLogic\Entity\Thing>) does not accept Doctrine\Common\Collections\ArrayCollection<(int|string), mixed>

Perhaps I'm just annotating things incorrectly, but I'm not sure what else to try now

```php
<?php

namespace EntityLogic\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use EntityLogic\Repository\TestEntityRepository;

#[ORM\Table(name: 'testentity')]
#[ORM\Entity(repositoryClass: TestEntityRepository::class)]
class TestEntity
{
    #[ORM\Column(name: 'id', type: 'integer', nullable: false)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'SEQUENCE')]
    #[ORM\SequenceGenerator(sequenceName: 'testentity_seq', allocationSize: 1, initialValue: 1)]
    private int $id;

    /**
     * @var Collection<int, Thing>
     */
    #[ORM\OneToMany(mappedBy: 'TestEntity', targetEntity: Thing::class)]
    private Collection $things;

    public function __construct()
    {
        $this->things = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Collection
     */
    public function getThings(): Collection
    {
        return $this->things;
    }

    /**
     * @param Collection $things
     *
     * @return TestEntity
     */
    public function setThings(Collection $things): TestEntity
    {
        $this->things = $things;

        return $this;
    }
}
```

My installed versions of things I guess might make a difference are....
PHP 8.1.2
phpstan/extension-installer           1.1.0 
phpstan/phpdoc-parser                 1.2.0 
phpstan/phpstan                            1.4.7 
phpstan/phpstan-doctrine             1.2.11
doctrine/collections     1.6.8
doctrine/common          3.2.2
doctrine/dbal            3.3.2
doctrine/orm             2.11.1

**Comment by philrennie** [comment]
If it helps, this started after I composer updated earlier today
```
Upgrading phpstan/phpstan (1.4.6 => 1.4.7)
Upgrading phpstan/phpstan-doctrine (1.2.10 => 1.2.11)
```

Before that I had collections type hinted as 

@var Collection<Entity> 

which I realise now was incorrect, but was not causing any notices from phpstan.
After the update, I was getting

Property $things (Collection<int, Thing>&iterable<Thing>) does not accept ArrayCollection<(int|string), mixed>

which makes sense, so I switched to the Collection<int, Entity> style, and am left with the current issue.

**Comment by ondrejmirtes** [comment]
Can you show me your phpstan.neon? And which rule level are you using?

**Comment by philrennie** [comment]
Sure, running on max using

```
parameters:
    level: max
    paths:
        - 'src'
    doctrine:
        objectManagerLoader: tests/ObjectManager.php
        reportDynamicQueryBuilders: false
```

We've been using phpstan for a couple of years as part of our git push hooks, always running on max and stopping the push on errors. I'm just now moving the project to PHP8 and phpstan 1.0 and ironing out the remaining kinks.
This project has been an absolutely essential tool for our code quality these last couple of years BTW, any mistakes that made it to production have been general business logic rather than coding errors thank to phpstan :D

**Comment by axzx** [comment]
same here

I have an entity
```php
    /** @var ArrayCollection<int, Category> */
    #[ORM\ManyToMany(targetEntity: Category::class)]
    #[ORM\JoinTable(name: 'pattern_categories')]
    #[Assert\Unique]
    private ArrayCollection $categories;

   public function __construct()
    {        
        $this->categories = new ArrayCollection();
    }

   /**
     * @return ArrayCollection<int, Category>
     */
    public function getCategories(): ArrayCollection
    {
        return $this->categories;
    }

    /**
     * @param iterable<Category> $categories
     */
    public function setCategories(iterable $categories): self
    {
        $this->categories->clear();

        foreach ($categories as $category) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }
```

phpstan level max

error

$categories (Doctrine\Common\Collections\ArrayCollection<int, App\Entity\Category>) does not accept Doctrine\Common\Collections\ArrayCollection<(int|string), mixed>.

**Comment by ondrejmirtes** [comment]
Should be fixed in PHPStan: https://github.com/phpstan/phpstan-src/commit/c2b9e713daa09db18111d28ba5c8cd79beeaeec5 Please test `phpstan/phpstan` dev-master once this builds: https://github.com/phpstan/phpstan-src/actions/runs/1930640905

**Comment by axzx** [comment]
Yes, it has been fixed.

thanks:)

**Comment by philrennie** [comment]
Yes, thank you Ondřej, this has cleared it up.
