### ISSUE TITLE
Different signatures on `getRepository()` method

### ISSUE THREAD

**Issue by PILLOWPET** [phpstan/phpstan-doctrine#303]
Hi,

We have an issue with the consistency of the phpstan analysis on our project across installations.

We have the following service called `DoctrineActiveRepository` :

```
<?php

declare(strict_types=1);

use Doctrine\Persistence\ManagerRegistry;
use Active\ActiveTranslation;

class DoctrineActiveRepository
{
    public function __construct(
        private ManagerRegistry $registry,
    ) {
    }

  public function batch(int $id) {
       $myTranslation = $this->registry->getRepository(ActiveTranslation::class)->find($id);
  }
}
```

On the first environment, I get the following error:
 `Call to an undefined method Doctrine\Persistence\ObjectRepository<Active\ActiveTranslation>::page().`

but on the second environment I get
`Call to an undefined method Doctrine\ORM\EntityRepository<Active\ActiveTranslation>::page()`

Both environments share the exact same versions of the packages:
```
phpstan/phpstan: 1.4.6
phpstan/phpstan-doctrine: 1.2.11
doctrine/orm: 2.9.6
doctrine/persistence: 2.3.0
```

I have tried reinstalling both environments with a fresh set of packages but haven't succeeded so far. I don't understand why both phpstan installations would not capture the same signature for the `getRepository` function

**Comment by ondrejmirtes** [comment]
Hi, what do you mean by "environments"? Is it the same project on different computers?

**Comment by PILLOWPET** [comment]
Yes same project but different computers

**Comment by ondrejmirtes** [comment]
Not sure why is it happening. `Doctrine\Persistence\ObjectRepository` is in the ManagerRegistry stub: https://github.com/phpstan/phpstan-doctrine/blob/master/stubs/Persistence/ManagerRegistry.stub

`Doctrine\ORM\EntityRepository` is returned by this extension https://github.com/phpstan/phpstan-doctrine/blob/master/src/Type/Doctrine/GetRepositoryDynamicReturnTypeExtension.php which has some complex logic in it.

My guess is that some exception is thrown and this catch is executed on one of the computers: https://github.com/phpstan/phpstan-doctrine/blob/9a1711a659829590f2ceb928674565258e176cbc/src/Type/Doctrine/GetRepositoryDynamicReturnTypeExtension.php#L111-L115

Feel free to debug that. Also try enabling bleedingEdge https://phpstan.org/blog/what-is-bleeding-edge, it might show some extra errors.

**Comment by PILLOWPET** [comment]
Thanks for your answer ! Any advice on how to debug the PHPStan process? I tried activating bleeding edge but nothing changed. I would like to setup a clean debug environment for the extension but I'm not sure where to start...

**Comment by ondrejmirtes** [comment]
Just put some var_dump()s in the extension in vendor/phpstan/phpstan-doctrine to see where it ends up.

**Comment by PILLOWPET** [comment]
I managed to find out why it was giving out different results. Some of the environments were running Composer 2.1.X and some were using Composer 2.2.X. 

As the documentation of [phpstan-extension-installer](https://github.com/phpstan/extension-installer) mentions, starting from Composer 2.2.0, composer prompts for an approval before installing extensions and we had:
```
"phpstan/extension-installer": false,
```
in our `composer.json`.

After changing this value to `true` and executing a fresh `composer install` the issue was gone.
