### ISSUE TITLE
Promoted properties from constructor do not seem to be parsed by phpstan-doctrine

### ISSUE THREAD

**Issue by Seldaek** [phpstan/phpstan-doctrine#306]
I got an error like:

`Property Entity\Foo::$type type mapping mismatch: database can contain string but property expects 'foo'|'bar'.` which is a known issue when having `self::TYPE_*` as var type.

But then I decided to move that property into the constructor like:

```
public function __construct(
        /**
         * @ORM\Column(type="string")
         * @var self::TYPE_*
         */
        private string $type,
) {
```

And the error above disappeared, which makes me assume that phpstan-doctrine does not see this property anymore as having doctrine mappings. Doctrine sees the property well though, and phpstan sees the type of `$this->type` correctly as `'foo'|'bar'` still. So it seems really specific to this lib.

**Comment by ondrejmirtes** [comment]
This was easy thanks to a virtual node ClassPropertyNode that represents both normal and promoted properties :) https://github.com/phpstan/phpstan-doctrine/commit/35b098cbf78647a15fcaf4a9bfa536b8de9c3ddd

Gonna release right away.

**Comment by Seldaek** [comment]
Thanks!
