### ISSUE TITLE
Feature request: Checking type hint of fields against Doctrine metadata

### ISSUE THREAD

**Issue by arnaud-lb** [phpstan/phpstan-doctrine#31]
phpstan-doctrine could check if a field's typehint matches Doctrine's metadata.

In the following example, the plugin could emit a warning telling that `int` does not match `string`:
```
/**
 * @var int
 *
 * @Column(type="string")
 */
 private $var;
```

In the following examples, the plugin could emit a warning telling that the field is nullable:

```
/**
 * @var int // Should be nullable
 *
 * @Column(type="integer", nullable=true)
 */
 private $var;

/**
 * @var Foo // Should be nullable
 *
 * @OneToOne(targetEntity="Foo")
```

**Comment by lookyman** [comment]
We have exactly this in our company, I might be able to release it publicly.

**Comment by ondrejmirtes** [comment]
It'd be cool to have it a part of phpstan-doctrine as rules.neon.

**Comment by lookyman** [comment]
Problem with this is it would most likely require to have doctrine in composer.json as a `require` dependency, so I'm thinking a separate package instead? Thoughts, @ondrejmirtes?

**Comment by ondrejmirtes** [comment]
This should now be possible in a nice way thanks to #49.

**Comment by ondrejmirtes** [comment]
Basic version for `@ORM\Column` implemented in #74 :)

**Comment by ondrejmirtes** [comment]
We consider this done :) #75 #76 Please test the hell out of it :)

**Comment by arnaud-lb** [comment]
Awesome ! Thanks @lookyman
