### ISSUE TITLE
Type mapping mismatch because database expects an other way

### ISSUE THREAD

**Issue by LucasLaurensMLP** [phpstan/phpstan-doctrine#317]
Hi everyone,

I use PHPStan in my project and i try to get the doctrine orm relation with attributes ex: 
```php
/** @var MyClassInterface|null $myProperty */
#[ORM\ManyToOne(targetEntity: MyClassInterface::class, inversedBy: 'an_other_property')]
#[ORM\JoinColumn(nullable: true)]
private ?MyClassInterface $myProperty;
```

However when I do this the terminal gives me an error:
`Property $myProperty type mapping mismatch: property can contain MyClassInterface|null but database expects MyClassEntity|null`.

And when I write it with annotations, it works. 
My relationship works on the site but PHPStan does not support this piece of code.
In some cases it works but not all the time (ex: when property is not nullable).

Any idea ?

**Comment by ondrejmirtes** [comment]
1) How does the code with PHPDoc annotations look like?
2) Do you have `objectManagerLoader` configured? https://github.com/phpstan/phpstan-doctrine#configuration

I don't understand the error message because your property is `ManyToOne`, there's no `Collection` referenced in the code but it is referenced in the error message.

**Comment by LucasLaurensMLP** [comment]
1. It looks like this
```php
/**
  * @var MyClassInterface|null $myProperty
  * @ORM\ManyToOne(targetEntity="MyClassInterface", inversedBy ="an_other_property")
  * @ORM\JoinColumn(nullable=true)
  */
private ?MyClassInterface $myProperty;
```
2. Yes, i have it
3. Sorry i update this part because i have a second error with the collection and i wrote the wrong one

**Comment by ondrejmirtes** [comment]
I don't understand how this code can report "Property $myProperty type mapping mismatch: property can contain MyClassInterface|null but database expects MyClassEntity|null." either, there isn't `MyClassEntity` mentioned anywhere.

**Comment by LucasLaurensMLP** [comment]
I agree with you 
I don't know why and this is my point 
I make it clear that this is an interface
For other properties it works but when it is nullable I feel that it does not work.

**Comment by LucasLaurensMLP** [comment]
Also when I talked about `MyClassEntity` it was to mean that it expects the class that implements the `MyClassInterface` and not the interface itself

**Comment by LucasLaurensMLP** [comment]
The solution that appears is in fact related to PHPStan updates.
There is no more need for the object-manager.php file.
So there is no need for configuration from a bundle.
Problem solved.

**Comment by ondrejmirtes** [comment]
Alright :)
