### ISSUE TITLE
use `@ORM\Entity(repositoryClass="…")` to resolve `EntityRepository<…>` implementation

### ISSUE THREAD

**Issue by CircleCode** [phpstan/phpstan-doctrine#318]
given the files

`MyEntity.php`
```php
<?php

namespace My;

/**
 * @ORM\Entity(repositoryClass="My\MyEntityRepository")
 */
class MyEntity
{
    /**
     * @ORM\Column(name="id", type="bigint")
     * @ORM\Id
     */
    protected $id;
}
```

`MyEntityRepository.php`
```php
<?php

namespace My;

use Doctrine\ORM\EntityRepository;

class MyEntityRepository extends EntityRepository
{
    public function customFunc(string $id): ?MyEntity
    {
        return $this->findById($id);
    }
}
```

`MyTest.php`
```php
<?php

namespace My;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class MyTest extends KernelTestCase
{
    public function foo()
    {
        /** @var EntityManagerInterface $em */
        $em = self::$container->get('doctrine.orm.entity_manager');
        $em->getRepository(MyEntity::class)->customFunc(1234);
    }
}
```

phpstan complains about `Call to an undefined method Doctrine\ORM\EntityRepository<My\MyEntity>::customFunc().` in `MyTest.php`.

As far as I understand the way this extension work, I thought that the annotation `@ORM\Entity(repositoryClass="My\MyEntityRepository")` would enable phpstan to know that the implementation of `\ORM\EntityRepository<My\MyEntity>` is given by `My\MyEntityRepository`.

Am I missing something?

**Comment by ondrejmirtes** [comment]
This already works as expected. Make sure to register `objectManagerLoader` as described in the README. If it doesn't help, create a small reproducing repo with your code that doesn't work.
