### ISSUE TITLE
`MAX(e.my_datetime_column) AS foo` is not inferred as \DateTime

### ISSUE THREAD

**Issue by yguedidi** [phpstan/phpstan-doctrine#321]
- Create an ORM QueryBuilder
- Call `->select('MAX(e.my_datetime_column) AS my_column')`
- Call `->getQuery()->getResult()`

See the type of `my_column` inferred as `string|null`

**Comment by arnaud-lb** [comment]
It think that this result is correct. Doctrine ORM doesn't reinterprets the type returned by the database driver for expressions.

If the database driver returns a `string` for `e.my_datetime_column`, Doctrine will return the `string`.

`MAX()` can also return `null` if there is no row in the group.
