### ISSUE TITLE
database can contain string but property expects class-string

### ISSUE THREAD

**Issue by darthf1** [phpstan/phpstan-doctrine#323]
Hi!

With 1.3.3 I get a new error, probably because I was using the property promotion in my class and its fixed in https://github.com/phpstan/phpstan-doctrine/commit/35b098cbf78647a15fcaf4a9bfa536b8de9c3ddd.

The error I get is:
```
Property MyClass::$eventClass type mapping mismatch: database can contain string but property expects class-string<MyInterface>.  
```
```php
class MyClass
{
    /**
     * @param class-string<MyInterface> $eventClass
     */
    private function __construct(
        private string $eventClass,
    ) {
    }
}
```
```php
$metadata->mapField(
    [
        'fieldName' => 'eventClass',
        'type' => 'string',
    ]
);
```

I would expect this to be okay; since `class-string` is a `string` and the doctrine type cannot be further specified.

**Comment by ondrejmirtes** [comment]
This is an expected error. "database can contain string" is a true statement - you have no guarantee that the database cannot inject something that isn't `class-string<MyInterface>` into your entity.

You can solve this by ignoring this error, or write a custom Doctrine type.

BTW arguably it's a bad idea to store implementation details like that in the database, it definitely makes working with it harder.
