### ISSUE TITLE
Error Doctrine\ORM\EntityManagerInterface::getClassMetadata()

### ISSUE THREAD

**Issue by louismariegaborit** [phpstan/phpstan-doctrine#347]
PHPStan version : 1.7.15
PHPStan Doctrine version : 1.3.9

I have this error `Parameter #1 $className of method Doctrine\ORM\EntityManagerInterface::getClassMetadata() expects class-string<object>, string given.` but the definition of the getClassMetadata accepts `string|class-string<T>`.

**Comment by ondrejmirtes** [comment]
You need to provide `class-string` when calling `getClassMetadata()`. Typehint `class-string` in your method, or check the value with `class_exists()` before passing it in `getClassMetadata`.
