### ISSUE TITLE
Call to an undefined method ... ObjectRepository::findOneByShortName().

### ISSUE THREAD

**Issue by tlorens** [phpstan/phpstan-doctrine#35]
Are magic methods not supported or is there some configuration option(s) I missed?

**Comment by ondrejmirtes** [comment]
Nope, they are not supported right now.

**Comment by tlorens** [comment]
Yeah, I found another post on it.. I'll just add it to the ignore list. .Thanks!

**Comment by ankitpp** [comment]
Error - Call to an undefined method object::something();

In this particular instance method was called after Instantiating an object from child class. Child class extends parent class but error was still thrown. 

**Parent** 
abstract class Duhh 
{
   public function something(){
    *Definition of Function in parent*
   }
}


**Child**
class DuhhChild extends Duhh
{
  
}

**Use of Method In Some Controller that throws PHP Stan Error - Call to an undefined method object::something();**

use DuhhChild;
class SomeController extends random
{
  $something = new DuhhChild;
  $something->something()
}


inorder to work around this error simple define a docBlock that explains that variable as an Instance of Child Class above the variable that you are using to Instantiate the object. Example;

use DuhhChild;
class SomeController extends random
{
 /** @var DuhhChild $something */
  $something = new DuhhChild;
  $something->something()
}

**Comment by ondrejmirtes** [comment]
@ankitpp This is completely unrelated to this issue and even to phpstan-doctrine, please open a new one in https://github.com/phpstan/phpstan/issues/new/choose
