### ISSUE TITLE
[>=1.8.3] Parameter #1 $func of method Doctrine\Common\Collections\Collection<int, X>::map() expects Closure(X=): Y, Closure(X): Y given.

### ISSUE THREAD

**Issue by gnutix** [phpstan/phpstan-doctrine#366]
Hello there!

Since upgrading from 1.8.2 to 1.8.5 (and tested only to 1.8.3), I've got some errors I'm not sure what I'm supposed to do with, so I thought I'd report them. Here's the demo (only the last inspection is relevant, the rest is copy/pasted from doctrine's code) : https://phpstan.org/r/11e031ea-d018-4a3f-a78a-6f941bf44284

The same error happens for about all the functions on Collection requiring a callable that we use in the project (map, filter, etc). Seems related to the usage of `=` in the closure definition.

Thanks for your insights !
gnutix

**Comment by ondrejmirtes** [comment]
Update doctrine/collections to the latest release and you're set.
