### ISSUE TITLE
Issues with doctrine/collection 1.8.0

### ISSUE THREAD

**Issue by gjuric** [phpstan/phpstan-doctrine#372]
After upgrading doctrine/collections from 1.7.3 to 1.8.0 I am seeing the following error:

```
Property FQCN\Account::$tags type mapping mismatch: property can contain
Doctrine\Common\Collections\Collection<int, FQCN\AccountTag> but database expects
Doctrine\Common\Collections\Collection&iterable<FQCN\AccountTag>.
```

Account::$tags is marked with 

```
/** @var Collection<int, AccountTag> */
private Collection $tags;
```

not sure what would be the correct way to mark this relation?

**Comment by ma-abdn** [comment]
I create a fix #373

**Comment by ondrejmirtes** [comment]
I tried to do a fix for the ReadableCollection (although I'm not sure it's related to this problem), can you please test phpstan-doctrine 1.3.15 to see if it fixes your problem? Thanks!

**Comment by gjuric** [comment]
v1.3.15 works, thank you!
