### ISSUE TITLE
Stubs aren't up-to-date with doctrine/collections 1.8.0 and 2.0.0

### ISSUE THREAD

**Issue by DesLynx** [phpstan/phpstan-doctrine#374]
Hi!
https://github.com/phpstan/phpstan-doctrine/blob/1.3.x/stubs/Collections/Collection.stub is not up to date with Collection interface from doctrine/collections (inheritance with a newly added ReadableCollection interface) and induce false-positive errors during analysis.
cf. Issue opened earlier at doctrine/collections https://github.com/doctrine/collections/issues/337#issuecomment-1262546250

**Comment by ondrejmirtes** [comment]
Fixed in phpstan-doctrine 1.3.15. Please test it and let me know :)

**Comment by DesLynx** [comment]
Hi!
No more false-positive errors :smile: 
Thanks for the fix
