### ISSUE TITLE
QueryBuilder->getQuery() return type conflicts with Psalm

### ISSUE THREAD

**Issue by annuh** [phpstan/phpstan-doctrine#377]
Since a recent release of the Psalm-doctrine plugin (https://github.com/psalm/psalm-plugin-doctrine/pull/115) the following code conflicts with Phpstan.

Can the new TKey parameter also be supported by the phpstan-docrine plugin? It looks like Psalm is more correct here.

Code:
```php
/** @var Query<array-key, Country> $query */
$query = $this->createQueryBuilder('country')->getQuery();
```

Without TKey (`/** @var Query<Country> $query */)` produces the following error in Psalm:
```
psalm: InvalidTemplateParam: Extended template param TKey of Doctrine\ORM\Query<App\Entity\Country\Country> expects type array-key, type App\Entity\Country\Country given
psalm: MissingTemplateParam: Doctrine\ORM\Query has missing template params, expecting 2
```

With TKey (`/** @var Query<array-key, Country> $query */`) procesed the following error in PHPStan:
```
phpstan: Generic type Doctrine\ORM\Query<(int|string), App\Entity\Country\Country> in PHPDoc tag @var for variable $query specifies 2 template types, but class Doctrine\ORM\Query supports only 1: TResult
```

**Comment by ondrejmirtes** [comment]
Yeah, feel free to update the stubs :)

**Comment by ondrejmirtes** [comment]
`Query<key, value>` is now supported: https://github.com/phpstan/phpstan-doctrine/commit/4490e56f6fe3f8985a03be073d4545c3fb59cdbb
