### ISSUE TITLE
Infering getResult as list

### ISSUE THREAD

**Issue by janedbal** [phpstan/phpstan-doctrine#381]
Hi, I'm currently testing upcoming version of phpstan (1.9.x-dev) where you cannot pass `array<Foo>` argument to `list<Foo>` parameter. Currently, simple queries like this
```php
$list = $qb->select('e')->from(Entity::class, 'e')->getResult();
```
are infered as `array<mixed, Entity>` ([source](https://github.com/phpstan/phpstan-doctrine/blob/1.3.x/src/Type/Doctrine/Query/QueryResultDynamicReturnTypeExtension.php#L129)) even though it is actually a list<Entity>. This is getting problematic in phpstan 1.9, would it be possible to return it as list when no `indexBy` is used? Or is there any blocker? 

I assume, this is mainly question for @arnaud-lb
Thank you

**Comment by VincentLanglet** [comment]
This can be closed @ondrejmirtes

**Comment by ondrejmirtes** [comment]
Thank you.
