### ISSUE TITLE
Infering Collection::toArray() as list

### ISSUE THREAD

**Issue by noemi-salaun** [phpstan/phpstan-doctrine#387]
With the new support for `list<>` type in PHPStan 1.9, I get a lot of false positive with collection associated with a simple OneToMany relation. When my relation is declared without `indexBy`, I know for a fact that `$myCollection->toArray()` will return a `list`.
I can use `getValues()` instead but it performs a useless `array_values` in this case. I don't know the performance of `array_values` on pure `list`.

**Comment by noemi-salaun** [comment]
I did a pretty naive performance test and it looks like `array_values` on a list is a no-op process.

```php
<?php

$myList = [];
$myArray = [];

for ($i = 0; $i < 1_000_000; $i++) {
    $random = random_int(PHP_INT_MIN, PHP_INT_MAX);
    $myList[] = $random;
    $myArray['foo' . ($i * 2)] = $random;
}

echo '$myList is a list? ' . (array_is_list($myList) ? 'yes' : 'no' ). "\n";
echo '$myArray is a list? ' . (array_is_list($myArray) ? 'yes' : 'no') . "\n";

$start = microtime(true);
array_values($myList);
echo 'array_values($myList) = ' . ((microtime(true) - $start) * 1000) . 'ms' . "\n";

$start = microtime(true);
array_values($myArray);
echo 'array_values($myArray) = ' . ((microtime(true) - $start) * 1000) . 'ms' . "\n";
```

> $myList is a list? yes
> $myArray is a list? no
> array_values($myList) = 0.0040531158447266ms
> array_values($myArray) = 20.13897895813ms

**Comment by ondrejmirtes** [comment]
PHPStan doesn't use ORM metadata to infer the type of collection. Doctrine PHPDocs themselves say this: `@psalm-return array<TKey,T>` so there's no guarantee it's gonna be a list.

There's no way to carry this information in generics either.

**Comment by bendavies** [comment]
> I know for a fact that $myCollection->toArray() will return a list.

no you don't. the underlying array is not guaranteed to be a list (you can remove and insert elements at any index)

`getValues` returns a `list<T>`, `toArray` returns `array<Tk, T>`.

sounds like you want to replace all your `toArray` calls with `getValues`

**Comment by noemi-salaun** [comment]
@bendavies you are right, I always forget the write part of Collection.
When I say "I know for a fact", I talk about this particular point in my code with a known context. But for a static analyser, I think it cannot be assured.
