### ISSUE TITLE
Problem after update 1.3.29 (phpstan 1.9.7)

### ISSUE THREAD

**Issue by szal1k** [phpstan/phpstan-doctrine#409]
Hi,
I have a problem after update:
phpstan/phpstan (1.9.6 => 1.9.7)
phpstan/phpstan-doctrine (1.3.28 => 1.3.29)

I use phpstan/extension-installer, and after update i see in console sucessfully extensions installed:
phpstan/extension-installer: Extensions installed
> ekino/phpstan-banned-code: installed
> phpstan/phpstan-doctrine: installed
> phpstan/phpstan-symfony: installed
> thecodingmachine/phpstan-strict-rules: installed

But when i run analyse, i have errors like: "Call to an undefined method App\Repository\BankRepository<App\Entity\Bank>::findOneByCode()."

Before update it works fine, now i think that extension doesn't work. Can i must do any changes in configuration?

------
Partially solved:
The problem is with doctrine/doctrine-bundle:2.8.2 and 2.8.1 in version 2.8.0 phpstan-doctrine works fine.

**Comment by ondrejmirtes** [comment]
Please create a small reproducing repository with the problem so I can decide who's fault it is and how to fix it 😊

**Comment by szal1k** [comment]
Ok, I send invitation to repository. 

See the sample: https://github.com/szal1k/phpstan-doctrine-issue409/blob/master/src/Controller/SampleController.php 

function "findOneById" report error with: phpstan analyse --level 9

**Comment by jamesisaac** [comment]
> Partially solved:
> The problem is with doctrine/doctrine-bundle:2.8.2 and 2.8.1 in version 2.8.0 phpstan-doctrine works fine.

Agreed, `doctrine/doctrine-bundle` v2.8.1 seems to have broken `phpstan-doctrine`'s ability to read repositories properly regardless of version.

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-doctrine/commit/e1437a270ed0512b69141729d7c4b3107946a1cf

Gonna release phpstan-doctrine 1.3.30 right away :)

**Comment by ondrejmirtes** [comment]
I had to rework this again, see https://github.com/phpstan/phpstan-doctrine/issues/413.

Please try PHPStan 1.9.11 + phpstan-doctrine 1.3.32 to see if it still works for you. Thanks.
