### ISSUE TITLE
Type mapping mismatch with string database field and enum like property type

### ISSUE THREAD

**Issue by yguedidi** [phpstan/phpstan-doctrine#423]
When the database field is of type string, but we type the entity property as an enum like type `@var MyEnum::*`, we get the type mapping mismatch error.
I think this case shouldn't lead to an error, or at least be allowed with a config parameter.

With this enum like:
```
class MyEnum
{
    public const FOO = 'foo';
    public const BAR = 'bar';
    public const BAZ = 'baz';
}
```

And this entity:
```
class MyEntity
{
    /**
     * @var MyEnum::*
     *
     * @ORM\Column(type="string", length=255)
     */
    private string $type;
}
```

The error looks like this:
```
Property App\Entity\MyEntity::$type type mapping mismatch: database can contain string but property expects 'foo'|'bar'|'baz'.
```

**Comment by ondrejmirtes** [comment]
Please show a code sample and a reported error.

**Comment by yguedidi** [comment]
@ondrejmirtes was updating the description, realizing that I posted too fast without much details, sorry for that!
Hope that now it's better

**Comment by ondrejmirtes** [comment]
This is expected. What the error is telling you that you might have `'lorem'` in your database table and Doctrine will happily use that value in your property.

You can solve this:

1) With a custom type.
2) By switching to native enum support that doesn't have this problem.
