### ISSUE TITLE
Doctrine custom filter method is undefined

### ISSUE THREAD

**Issue by szal1k** [phpstan/phpstan-doctrine#424]
Hi,
I have problem with custom method in class extends Doctrine\ORM\Query\Filter\SQLFilter.

My Filter class with custom method:

```
<?php

use Doctrine\ORM\Query\Filter\SQLFilter;

class ArchiveableFilter extends SQLFilter
{

    protected $enabledOnlyForEntity = [];

    public function addFilterConstraint(ClassMetadata $targetEntity, $targetTableAlias)
    {        
        ...
    }

    public function enableOnlyForEntity($class)
    {
        $this->enabledOnlyForEntity[$class] = true;
    }
}
```

And when I use it:

`$filter = $this->em->getFilters()->enable("archiveable");`
`$filter->enableOnlyForEntity("App\Entity\Unit");`

In phpstan get "Call to an undefined method Doctrine\ORM\Query\Filter\SQLFilter::enableOnlyForEntity()."

Any ideas for it?

Thanks for your help.

**Comment by ondrejmirtes** [comment]
PHPStan doesn't know that `$this->em->getFilters()->enable("archiveable")` returns your `ArchiveableFilter`.

This might be solvable with a dynamic return type extension.

**Comment by szal1k** [comment]
Thanks!
