### ISSUE TITLE
Strange workaround to avoid ReadableCollection error

### ISSUE THREAD

**Issue by Sinjonathan** [phpstan/phpstan-doctrine#428]
HI,

After upgrading doctrine/collections (1.7.2 => 2.1.2), i get this new error when i try to use filter on my $employees collection:

```
Property App\Entity\Institution::$employees                                          
(Doctrine\Common\Collections\Collection&iterable<App\Entity\UserCustomer>) does not  
accept Doctrine\Common\Collections\ReadableCollection<(int|string), mixed>.
```

My entity is configured like this :
```
/**
 * @var Collection<UserCustomer>
 */
private Collection $employees;

public function __construct()
{
    $this->employees = new ArrayCollection();
}
```

And my filter is used in getter function :
```
public function getEmployees(bool $filterUnactivatedEmployees = true): Collection
{
    if ($filterUnactivatedEmployees) {
        $this->employees = $this->employees->filter(fn (UserCustomer $userCustomer) => my_condition );
    }

    return $this->employees;
}
```

I have the following parameters for phpstan ( phpstan/phpstan-doctrine version is 1.3.32) :
```
parameters:
    inferPrivatePropertyTypeFromConstructor: true
    checkGenericClassInNonGenericObjectType: false
```

Now i have multiples solutions but they seem incorrect to my eyes

Fisrt one, simply typehint $employees as ArrayCollection in the docblocs
```
/**
 * @var ArrayCollection<UserCustomer>
 */
private Collection $employees;
```

But here property's type and docblocs are not in sync.

Another solution is to force the instanciation of a new ArrayCollection before to call filter function

```
public function getEmployees(bool $filterUnactivatedEmployees = true): Collection
{
    if ($filterUnactivatedEmployees) {
        $this->employees = new ArrayCollection($this->employees->filter(fn (UserCustomer $userCustomer) => my_condition )-> toArray());
    }

    return $this->employees;
}
```

But here we now can't chain method easily if necessary ( collection->filter()->add() )

Here a playground that reproduce the problem : https://phpstan.org/r/b2b34823-1c23-47cf-9f55-9a37de2e2c50

Did i do something wrong ? Which solution sould I use to avoid this error ? One of mine, another ? 
Should i ask doctrine/collections instead ?

Thank for your time.

**Comment by ondrejmirtes** [comment]
I'd recommend you to report this in doctrine/collections repository. `interface Collection` should probably override the `filter` method with a better `@return`.
