### ISSUE TITLE
TreeWalker::walkSelectStatement return is being omitted 

### ISSUE THREAD

**Issue by oleg-andreyev** [phpstan/phpstan-doctrine#433]
```
Return type (void) of method App\ElasticSearch\WhereGteWalker::walkSelectStatement() should be compatible with return type (string) of method  
         Doctrine\ORM\Query\TreeWalker::walkSelectStatement() 
```

Original:
https://phpstan.org/r/e87d86de-1d75-4a84-a6bb-aa1fa13294cc
Try to implement void
https://phpstan.org/r/27daee9c-6d86-4be3-900f-c3a86da2366c
Try to implement string
https://phpstan.org/r/27daee9c-6d86-4be3-900f-c3a86da2366c

CustomWalker extends TreeWalkerAdapter which implements TreeWalker.
TreeWalker defines walkSelectStatement return string
TreeWalkerAdapter defines walkSelectStatement return void

**Comment by ondrejmirtes** [comment]
I don't understand the problem. When the interface returns string, your implementation also needs to return string: https://phpstan.org/r/abbebcbc-a548-4251-a752-32080f000ecb
