### ISSUE TITLE
Reflection error: Could not locate constant in version 1.3.36

### ISSUE THREAD

**Issue by lukasojd** [phpstan/phpstan-doctrine#435]
Hi, 

When i changed version from 1.3.35 to 1.3.36.

I got a lot of errors:

  57     Reflection error: Could not locate constant App\Enum\Status::PUBLIC  
         while trying to evaluate constant expression in class App\Entity\Project in file              
         /app/src/Entity/Project.php (line 49) 

Example usage:
``
	#[ORM\Column(type: Types::STRING, length: 255, enumType: Status::class, options: [
		'default' => Status::PUBLIC,
	])]
	private Status $subType;
```

**Comment by ondrejmirtes** [comment]
Is there `App\Enum\Status::PUBLIC` in your code?

**Comment by ondrejmirtes** [comment]
Anyway, I'd like to see a reproduction. Can you please create a small reproducing repository that shows the problem? Thank you.

**Comment by lukasojd** [comment]
@ondrejmirtes Yes, it is. I going to try to create it.

**Comment by lukasojd** [comment]
@ondrejmirtes I created repo with bug https://github.com/lukasojd/phpstan-bug

When I removed include ( vendor/phpstan/phpstan/conf/bleedingEdge.neon ) from phpstan.neon, everythink is OK. 

When i upgraded package down to 1.3.35, everything is OK. 

When I changed 
```
#[ORM\Column(type: Types::STRING, length: 255, enumType: Status::class, options: [
'default' => Status::PUBLIC,
])]
private Status $subType;
```
to
```
#[ORM\Column(type: Types::STRING, length: 255, enumType: Status::class, options: [
'default' => 'public',
])]
private Status $subType;
```
Phpstan is OK.

**Comment by ondrejmirtes** [comment]
Thank you. I thought the change made sense and was going to be better, but I decided to revert it: https://github.com/phpstan/phpstan-doctrine/commit/62bd362b432fe29e175168689510ddd927b698f8

**Comment by lukasojd** [comment]
@ondrejmirtes Thank you, I upgraded phpstan/phpstan-doctrine to 1.3.37 and everything is OK.
