### ISSUE TITLE
EntityManager::getReference() and getPartialReference() do not return null

### ISSUE THREAD

**Issue by arnaud-lb** [phpstan/phpstan-doctrine#45]
`ObjectManagerFindDynamicReturnTypeExtension` sets the return type of `getReference()` and `getPartialReference()` to nullable. However, these methods never return null.

**Comment by ondrejmirtes** [comment]
According to the documentation https://www.doctrine-project.org/api/orm/latest/Doctrine/ORM/EntityManager.html#method_getReference, they do.

**Comment by ondrejmirtes** [comment]
I even checked the source code - https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/EntityManager.php#L510

**Comment by arnaud-lb** [comment]
Oh, my mistake then. Thanks :)
