### ISSUE TITLE
Internal error: Internal error: Context: Using short namespace alias "xxx" by calling

### ISSUE THREAD

**Issue by gjuric** [phpstan/phpstan-doctrine#450]
With the release of Doctrine ORM 2.14.2 they started throwing exception when short aliases are defined, see https://github.com/doctrine/orm/pull/10489

I am opening the issue here since it looks like these exceptions were supposed the be thrown previously as well.

The error I am seeing in phpstan after removing short aliases from the Doctrine configuration look like this:

```
     Internal error: Internal error: Context: Using short namespace alias "MyShortAlias" by calling
     Doctrine\ORM\Configuration::addEntityNamespace
     Problem: Feature was deprecated in doctrine/persistence 2.x and is not supported by installed doctrine/persistence:3.x
     Solution: See the doctrine/deprecations logs for new alternative approaches.
```

My code is still probably using short aliases somewhere in the DQL, but I wanted to use PHPStan to point to those.

**Comment by ondrejmirtes** [comment]
Please run with `--debug`, you should see a complete stack trace & paste it here.

**Comment by gjuric** [comment]
Sorry, my bad, It looks like my Symfony DIC definition in the cache didn't get rebuilt before running PHPStan. Everything works now.
