### ISSUE TITLE
Allow higher versions of `doctrine/lexer`

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-doctrine#457]
Hey there :wave: 

I just wanted to know, if it would be possible to allow also higher versions of `doctrine/lexer`? 
Right now, we are installing PHPStan and its extensions along with `doctrine/orm`, etc. but the newest versions of those packages are requiring version 2 of `doctrine/lexer`. 

I have not looked it up yet, how lexer is used here, but if it would be possible, I would like to provide a PR for that. 

Bes regards

**Comment by ondrejmirtes** [comment]
`phpstan/phpstan-doctrine` doesn't require nor limit any version range of `doctrine/*`: https://github.com/phpstan/phpstan-doctrine/blob/6c4910dc1a9d47d3546674f8c2748e2879ee448f/composer.json#L8-L11

So I'm not sure what you're actually asking :)

**Comment by mitelg** [comment]
oh sorry, it only happens, if you install with `require-dev`, which is the case, when we want to install PHPStan

**Comment by ondrejmirtes** [comment]
I don't get it. Please show a series of `composer` commands that lead to the error you're experiencing versus what output would you expect.

**Comment by mitelg** [comment]
sorry for that. I think I was on the wrong way :see_no_evil: sorry for the distraction

**Comment by mitelg** [comment]
btw. if I saw that correctly, the lexer dependency is not used directly here. so it could be removed at all :slightly_smiling_face:
