### ISSUE TITLE
Using resolveTargetEntity causes type mismatch error

### ISSUE THREAD

**Issue by aszenz** [phpstan/phpstan-doctrine#476]
Using [resolveTargetEntity](https://symfony.com/doc/current/doctrine/resolve_target_entity.html) feature of doctrine causes mismatch error:

```
->resolveTargetEntity(OrderIncomingLineInterface::class, IncomingOrderLine::class)
```

Property App\Entity\ProductPercentagesPerCountry::$incomingLine type mapping mismatch: property can contain App\Entity\Shared\OrderIncomingLineInterface but database expects App\Entity\IncomingOrderLine on this line of code.

```php
 #[ManyToOne(targetEntity: OrderIncomingLineInterface::class, inversedBy: 'productPercentages')]
 #[JoinColumn(name: 'stock_id', referencedColumnName: 'id', nullable: false)]
 private OrderIncomingLineInterface $incomingLine;
```

**Comment by ondrejmirtes** [comment]
I'd say this works as expected. Without `resolveTargetEntity` you wouldn't get an error because `targetEntity: OrderIncomingLineInterface::class` and property type `OrderIncomingLineInterface` are the same.

But because you called `resolveTargetEntity` it's now `IncomingOrderLine` in `targetEntity` metadata but still `OrderIncomingLineInterface` in the property type, resulting in this error.

So with your `->resolveTargetEntity` call what Doctrine and phpstan-doctrine now see is essentially:

```
 #[ManyToOne(targetEntity: IncomingOrderLine::class, inversedBy: 'productPercentages')]
 #[JoinColumn(name: 'stock_id', referencedColumnName: 'id', nullable: false)]
 private OrderIncomingLineInterface $incomingLine;
```

Which results in the expected error:

```
Property App\Entity\ProductPercentagesPerCountry::$incomingLine type mapping mismatch: property can contain App\Entity\Shared\OrderIncomingLineInterface but database expects App\Entity\IncomingOrderLine
```

**Comment by aszenz** [comment]
> I'd say this works as expected. Without `resolveTargetEntity` you wouldn't get an error because `targetEntity: OrderIncomingLineInterface::class` and property type `OrderIncomingLineInterface` are the same.
> 
> But because you called `resolveTargetEntity` it's now `IncomingOrderLine` in `targetEntity` metadata but still `OrderIncomingLineInterface` in the property type, resulting in this error.
> 
> So with your `->resolveTargetEntity` call what Doctrine and phpstan-doctrine now see is essentially:
> 
> ```
>  #[ManyToOne(targetEntity: IncomingOrderLine::class, inversedBy: 'productPercentages')]
>  #[JoinColumn(name: 'stock_id', referencedColumnName: 'id', nullable: false)]
>  private OrderIncomingLineInterface $incomingLine;
> ```
> 
> Which results in the expected error:
> 
> ```
> Property App\Entity\ProductPercentagesPerCountry::$incomingLine type mapping mismatch: property can contain App\Entity\Shared\OrderIncomingLineInterface but database expects App\Entity\IncomingOrderLine
> ```

Ok, that makes more sense, I can see how it works as expected in a way.

How would you recommend handling this error, I don't want to reference `IncomingOrderLine` in my entity for decoupling purposes, should i just ignore the error or is their a way to disable this rule for `resolveTargetEntity` usage

**Comment by ondrejmirtes** [comment]
I don't really understand what this is about, why do you need `resolveTargetEntity` at all, and how `IncomingOrderLine` and `OrderIncomingLineInterface` are related.

As it currently is your code is unsafe. Your property accepts `OrderIncomingLineInterface` but Doctrine expects `IncomingOrderLine`.

**Comment by aszenz** [comment]
> As it currently is your code is unsafe. Your property accepts OrderIncomingLineInterface but Doctrine expects IncomingOrderLine.

Resolvetargetentity is a feature provided by doctrine, see https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/cookbook/resolve-target-entity-listener.html#keeping-your-modules-independent

The idea is to make an interface for an entity, implement it in your entity, and use the interface to link it with other entities.

This is useful to prevent huge object graphs and helps in unit testing u don't need to instantiate dependent entities.

**Comment by ondrejmirtes** [comment]
Yes but form PHP standpoint you can put something else in `private OrderIncomingLineInterface $incomingLine;` that isn't `IncomingOrderLine` and no one's there to stop you. That's why PHPStan reports this as a problem.
