### ISSUE TITLE
Bigint are casted to int (if possible) for DBAL 4

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-doctrine#484]
With https://github.com/doctrine/dbal/pull/6177, the bigint will now be casted to `int` by doctrine.
So I assume the BigIntType will need to be updated for Doctrine 4.

I assume 
https://github.com/phpstan/phpstan-doctrine/blob/39d78ad7ca5386acf71f727b9ae5ae5979a5e1ea/src/Type/Doctrine/Descriptors/BigIntType.php#L21
need to be changed at least from numeric-string to numeric "if DBAL version is 4".

Or should it be `BenevolentUnion(int, numeric)` because most of users use them for small enough values (?).

**Comment by ondrejmirtes** [comment]
Relevant discussion: https://github.com/doctrine/dbal/pull/6177#issuecomment-1801793450

**Comment by VincentLanglet** [comment]
> Relevant discussion: [doctrine/dbal#6177 (comment)](https://github.com/doctrine/dbal/pull/6177#issuecomment-1801793450)

If I understand correctly the discussion, the bigint is
- An int on PHP 64 bit
- An int on PHP 32 bit if not UNSIGNED.
- An int|numeric-string on PHP 32 bit if UNSIGNED.

**Comment by ondrejmirtes** [comment]
Implemented: https://github.com/phpstan/phpstan-doctrine/pull/535/commits/719a8f40cb747dad1c37b8dc1ce4c60368c791a1
