### ISSUE TITLE
`Property X::$y is never written, only read.` on generated column

### ISSUE THREAD

**Issue by marc-mabe** [phpstan/phpstan-doctrine#508]
Hi,

We have a generated column on MySQL propagated via `ADD COLUMN xxx VARCHAR(45) GENERATED ALWAYS AS (REGEXP_REPLACE(LOWER(`name`), '[^a-z0-9+]', ''))`.

It's not a primary key and we do need this column value in Doctrine but as it's a generated we'll never write it's value.
For that we use the new feature of Doctrine 2.11 for such cases and the property is defined as follows:

```
#[ORM\Entity]
class Foo
{
    #[ORM\Id, ORM\Column, ORM\GeneratedValue]
    private ?string $id = null;

    #[ORM\Id, ORM\Column]
    private string $name;

    #[ORM\Column(name: '`key`', type: 'string', insertable: false, updatable: false, generated: 'ALWAYS')]
    private string $key;

    /** @phpstan-param non-empty-string $name */
    public function __construct(
        string $name,
    ) {
        $this->setName($name);
    }

    public function getId(): string
    {
        return $this->id ?? throw new \LogicException(
            'Foo.id is available only after flushing new entities to DB'
        );
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getKey(): string
    {
        return $this->key;
    }
}
```

**Comment by ondrejmirtes** [comment]
This extension can be adjusted to account for this https://github.com/phpstan/phpstan-doctrine/blob/1.4.x/src/Rules/Doctrine/ORM/PropertiesExtension.php

**Comment by marc-mabe** [comment]
> This extension can be adjusted to account for this https://github.com/phpstan/phpstan-doctrine/blob/1.4.x/src/Rules/Doctrine/ORM/PropertiesExtension.php

Not sure what I have done wrong but now it's working fine :+1:
