### ISSUE TITLE
doctrine/orm v3 - Declaration of ClassMetadataFactory::newClassMetadataInstance($className)

### ISSUE THREAD

**Issue by lugosium** [phpstan/phpstan-doctrine#530]
Hello,

Got this error after upgrading to ORM v3:

Child process error (exit code 255): Fatal error: Declaration of PHPStan\Doctrine\Mapping\ClassMetadataFactory::newClassMetadataInstance($className) must be compatible with
     Doctrine\ORM\Mapping\ClassMetadataFactory::newClassMetadataInstance(string $className): Doctrine\ORM\Mapping\ClassMetadata in
     vendor/phpstan/phpstan-doctrine/src/Doctrine/Mapping/ClassMetadataFactory.php on line 60

**Comment by VincentLanglet** [comment]
Currently ORM v3 is not supported, I took a look and it's not easy  to fix (https://github.com/phpstan/phpstan-doctrine/pull/531)

**Comment by ondrejmirtes** [comment]
Hello, phpstan-doctrine is not yet fully compatible and verified to work with Doctrine ORM 3.0 and DBAL 4.0, but I did some work to make forward-compatible changes that should work both with old and new versions: https://github.com/phpstan/phpstan-doctrine/compare/9534fcd0b6906c62594146b506acadeabd3a99b3...30cf38dda057a78180c4df1f6f41e33eb49c4eca

These changes have just been released in phpstan-doctrine 1.3.60: https://github.com/phpstan/phpstan-doctrine/releases/tag/1.3.60 Please report back how they work for you, thanks.

The work on full compatibility with Doctrine ORM 3.0 and DBAL 4.0 continues in https://github.com/phpstan/phpstan-doctrine/pull/535.

**Comment by ondrejmirtes** [comment]
Please continue the discussion in https://github.com/phpstan/phpstan-doctrine/issues/529, thanks.
