### ISSUE TITLE
Since v1.3.64: Interface "PHPStan\Classes\ForbiddenClassNameExtension" not found

### ISSUE THREAD

**Issue by andythedandy** [phpstan/phpstan-doctrine#558]
When I run phpstan with this extension since version 1.3.64 I get following error (which is indeed right as this interface doesn't exist):

```
In Resolver.php line 349:
                                                                               
  Service (PHPStan\Classes\DoctrineProxyForbiddenClassNamesExtension::__const  
  ruct()): Interface "PHPStan\Classes\ForbiddenClassNameExtension" not found   
                                                                               
In DoctrineProxyForbiddenClassNamesExtension.php line 8:
                                                                     
  Interface "PHPStan\Classes\ForbiddenClassNameExtension" not found  
```

**Comment by ondrejmirtes** [comment]
How did you install PHPStan and how did you install phpstan-doctrine? Seems like somehow you combined incompatible versions, but Composer does not allow you to do this.

**Comment by andythedandy** [comment]
We had that already in our composer.json file and I just did an "composer update phpstan/phpstan-doctrine". That was basically all.

**Comment by andythedandy** [comment]
Ah...I see....We're running PHPStan from another docker image. Ok. Then this is probably the problem. Haven't had that in mind.

**Comment by ondrejmirtes** [comment]
It doesn't make sense to do that. Installing phpstan-doctrine will install phpstan/phpstan in your project too.

**Comment by andythedandy** [comment]
You're absolutely right. This is some legacy fu in our code base that need to be fixed. Thanks a lot! I'll close this.
