### ISSUE TITLE
GetRepository return value mismatch for ODM\GridFSDocument

### ISSUE THREAD

**Issue by josefsabl** [phpstan/phpstan-doctrine#59]
I have this code:

```
$repository = $this->documentManager->getRepository(Document::class);
assert($repository instanceof \Doctrine\ODM\MongoDB\Repository\DefaultGridFSRepository);
```

The assert passes but I get this PhpStan error:

```
Instanceof between                                                   
Doctrine\ORM\EntityRepository<MyCompany\ODM\File\Document> and           
Doctrine\ODM\MongoDB\Repository\DefaultGridFSRepository will always  
evaluate to false. 
```

Note that the document for which I am getting a repository is not a standard document but rather GridFS file document which has some specifics.

The code snippet is taken from [here](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/storing-files-with-mongogridfs.html#inserting-files-into-gridfs-buckets).

**Comment by alcaeus** [comment]
Are you using the 2.0 beta version? I don’t believe the code for this has been updated to cover 2.0.

**Comment by josefsabl** [comment]
> Are you using the 2.0 beta version?

Yes I am. Okay, thank you very much!

**Comment by ondrejmirtes** [comment]
Please try the latest version and report back, thanks.
