### ISSUE TITLE
Compatibiliy with EntityRepository::createQueryBuilder

### ISSUE THREAD

**Issue by edafonseca** [phpstan/phpstan-doctrine#66]
Hello,
It seems that query builders built with `\Doctrine\ORM\EntityRepository::createQueryBuilder` are not validating DQL, only ones built with `\Doctrine\ORM\EntityManagerInterface::createQueryBuilder`.

I'm trying to analyse a Symfony 4 project where all queryBuilder are created within repository classes with `$this->createQueryBuilder`.
Am I missing something ?

Thanks

**Comment by andreybolonin** [comment]
@edafonseca @ondrejmirtes any ideas how to validate this one (`\Doctrine\ORM\EntityRepository::createQueryBuilder`)?

<img width="701" alt="Screen Shot 2019-10-13 at 12 42 43 PM" src="https://user-images.githubusercontent.com/2576509/66713721-fb739e80-edb6-11e9-97e8-9fdf7af02e70.png">

**Comment by ondrejmirtes** [comment]
It should be possible to validate the ones built with `\Doctrine\ORM\EntityRepository::createQueryBuilder` too (it's a matter of writing a dynamic return type extension), I don't have time for it now though.
