### ISSUE TITLE
Support for Repositories as a Services (Symfony)

### ISSUE THREAD

**Issue by Kocal** [phpstan/phpstan-doctrine#67]
Hi, this feature request follows https://github.com/phpstan/phpstan-doctrine/issues/65#issuecomment-509661033 and https://github.com/phpstan/phpstan-doctrine/issues/65#issuecomment-509799147.

Since Symfony 4.0, it is possible to define [Repositories as as Service](https://symfonycasts.com/screencast/symfony4-upgrade/extras#repositories-as-a-service) by extending from `ServiceEntityRepository` like this:

```php
<?php

namespace App\Repository\User;

use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * @method User|null find($id, $lockMode = null, $lockVersion = null)
 * @method User|null findOneBy(array $criteria, array $orderBy = null)
 * @method User[]    findAll()
 * @method User[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class UserRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, User::class);
    }
}
```

And we can accessing it directly from services constructor or constroller's actions with type hinting:

```php
<?php

namespace App\Controller;

use App\Repository\User\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(UserRepository $userRepository)
    {
        $user = $userRepository->find(123);
        $user->getFooBar();
    }
}
``` 

But there are some issues.

If we use this phpstan extension, calling whatever method on `$user` that does not exist on `App\Entity\User` will not fails.

If we don't use it, `$userRepository->find*` methods will works correctly (due to `@method` annotations, but they are needed for PHPStorm too) and we will see the error `Cannot call method getFooBar() on App\Entity\User|null.`

As said in the issue, we can use `/** @var App\Repository\UserRepository<App\Entity\User> */` to make phpstan works, but:
- this is verbose, we have to add it everytime we inject a repository as service dependency
- this is non sense, since the type is `UserRepository`, phpstan should be able to works with it

To make it work, this extension (or the Symfony extension?) should:
- Find classes that extends from `ServiceEntityRepository`
- Get the entity type from constructor 2nd parameter
- And do some magic :sparkles: 

In fact, I think it would be better if the repositories detection is part of Symfony extension. Since the Symfony extension can access the Symfony container, we can find services tagged with `doctrine.repository_service` and then use them: 
![Capture d’écran de 2019-07-10 06-37-23](https://user-images.githubusercontent.com/2103975/60940844-3f00cd00-a2dd-11e9-93ba-0025e1027ab3.png)

What do you think?

Thanks! :)

**Comment by mikysan** [comment]
I'm not sure I understood the problem but actually getting `Cannot call method getFooBar() on App\Entity\User|null.` is the right behavior because find* methods could indeed return null values (or empty array, depends on which find method you are using).
Infact in your example if you handle the null value the phpstan error should be suppressed, ie:
```
<?php

namespace App\Controller;

use App\Repository\User\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(UserRepository $userRepository)
    {
        $user = $userRepository->find(123);
        if (null === $user) {
            throw new NotFoundHttpException('User not found.');
        }
        $user->getFooBar();
    }
}

```

**Comment by VincentLanglet** [comment]
The comment 
```
/**
 * @method User|null find($id, $lockMode = null, $lockVersion = null)
 * @method User|null findOneBy(array $criteria, array $orderBy = null)
 * @method User[]    findAll()
 * @method User[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
```

Fix the issue for me

**Comment by ondrejmirtes** [comment]
Hi, the right solution is to have `/** @extends ServiceEntityRepository<User> */` above your UserRepository. That lets PHPStan know everything it needs.
