### ISSUE TITLE
Hard dependency on doctrine/orm makes in impossible to use only with doctrine/common

### ISSUE THREAD

**Issue by Majkl578** [phpstan/phpstan-doctrine#7]
_As the title says._

Maybe the package should be split to phpstan-doctrine-collections and phpstan-doctrine-orm?

**Comment by JanTvrdik** [comment]
IMHO this package should not depend on `doctrine/*` at all.

**Comment by ondrejmirtes** [comment]
Most of this package is about `Doctrine\ORM` support. If you need just the `Selectable` interface handled, just copy that extension into your codebase :)
