### ISSUE TITLE
Discriminator detection

### ISSUE THREAD

**Issue by darthf1** [phpstan/phpstan-doctrine#93]
Hi,

I have an `abstract class BasicFile` which is used as a Discriminator with Single Table Inheritance.
https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/inheritance-mapping.html#single-table-inheritance

```
<?php
/**
 * @ORM\Table(name="files")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"data" = "DataFile"})
 */
abstract class BasicFile {}
```

And my entity:
```
<?php
/*
 * @ORM\Entity
 */
class DataFile extends BasicFile {}
```

When I initiate a method on the `DataFile` entity, which is not available on the `BasicFile` class, i get an error stating the method does not exist.

```
<?php
$dataFile = new DataFile();
$dataFile->setName('xxx');

Call to an undefined method App\Entity\BasicFile::setName().
```

Using:
Symfony 5.0.1
doctrine/orm: 2.7.0
phpstan-shim: 0.11.19
phpstan-doctrine: 0.11.6

**Comment by ondrejmirtes** [comment]
Hi, I don't see how this would be possible. Are you sure this is the exact source code that's causing your issue?

Also, you should upgrade to `phpstan/phpstan` 0.12 (not the shim version, that's obsolete).

**Comment by darthf1** [comment]
Yeah i'm sure this is the exact code.

I already tried `0.12` but the new `level 6` was too hard for me at the moment. With 0.11 i can stay on max level ;). I'll try the upgrade to `0.12` again later (probably Monday) and see if this specific error is still there.

**Comment by ondrejmirtes** [comment]
There's no code that would override what `new` resolves to. Are you sure you don't have any dynamic return type extension?

The code is equivalent to this: https://phpstan.org/r/1a519eac-4187-4324-a8bd-f90ec1a9255e

> the new level 6 was too hard for me

Yeah, but the max level on 0.11 is just an illusion if you have missing typehints :) People with no typehints can have max level but without anything actually checked.

Also make sure you learn about the baseline feature, it can help you to upgrade to 0.12 without actually fixing all the errors :) Check out my blog for the latest three articles: medium.com/@ondrejmirtes/

**Comment by darthf1** [comment]
You're absolutely right, this has nothing to do with phpstan; I'm using fluent getters/setters, so i got returned the `BasicFile class` and then used a `DataFile` function on that class. 

Updated example: https://phpstan.org/r/b3099a50-14a4-4029-94ef-c54b79e40ea4

> 
> Yeah, but the max level on 0.11 is just an illusion if you have missing typehints :) People with no typehints can have max level but without anything actually checked.
> 
I have return typehints and return types everywhere, but I'm using a lot of generic array types. 

Thanks! Going to read the articles.

**Comment by ondrejmirtes** [comment]
You need `@return static`: https://phpstan.org/r/9ea9df54-67c6-4336-b1ad-b67c573c050f
