### ISSUE TITLE
Support ResolveTargetEntityListener

### ISSUE THREAD

**Issue by alexander-schranz** [phpstan/phpstan-doctrine#98]
We are using the [ResolveTargetEntityListener](https://github.com/sulu/sulu/blob/122a5d02b438c1ec08fd72b81e1ae47427c5c007/src/Sulu/Bundle/PersistenceBundle/DependencyInjection/Compiler/ResolveTargetEntitiesPass.php#L56-L57) of doctrine to allow using interfaces and it allows us to overwrite entities without using mapping superclass behaviour e.g.:

```xml
<many-to-one
    field="directory"
    target-entity="Sulu\Bundle\MyBundle\Model\DirectoryInterface"
    inversed-by="translations"
>
    <join-column name="directoryNo" referenced-column-name="no" on-delete="CASCADE" nullable="false"/>
</many-to-one>
```

```php
    /**
     * @var DirectoryInterface
     */
    private $directory;
```

This ends currently with:

> Sulu\Bundle\MyBundle\Model\DirectoryTranslation::$directory type mapping mismatch: property can contain Sulu\Bundle\MyBundle\Model\DirectoryInterface but database expects Sulu\Bundle\MyBundle\Model\Directory.

It would be awesome if it would take the Interface instead of the resolved entity so that phpstan would not error for resolved.

**Comment by ondrejmirtes** [comment]
Hi, phpstan-doctrine uses what the provided EntityManager tells it. Can you give it the EntityManager that would tell it about the `target-entity="Sulu\Bundle\MyBundle\Model\DirectoryInterface"`?

**Comment by thomasvargiu** [comment]
This is what I did:

```php
/** @var \Doctrine\ORM\EntityManager $objectManager */
$objectManager = $container->get(\Doctrine\Common\Persistence\ObjectManager::class);

$entityResolver = current(array_filter(
    $objectManager->getEventManager()->getListeners('loadClassMetadata'),
    static function ($listener) {
        return $listener instanceof \Doctrine\ORM\Tools\ResolveTargetEntityListener;
    }
));

$objectManager->getEventManager()->removeEventSubscriber($entityResolver);
```

But phpstan-doctrine can't resolve repositories from interfaces.

An idea could be to read the mapping from the `ResolveTargetEntityListener` with reflection, and enable the original mapped type (interface) as allowed property type.
